import type { ActivityIssue } from "../generated/ActivityIssue";

export const activityMessages: Record<ActivityIssue, string> = {
  activity_consent_save_failed: "수집 설정을 저장하지 못했습니다. 현재 수집 상태를 확인하고 다시 시도해 주세요.",
  autostart_owner_conflict: "다른 실행 파일의 시작프로그램 등록이 있어 변경하지 않았습니다.",
  autostart_owner_invalid: "현재 설치의 시작프로그램 등록 정보를 확인하지 못했습니다.",
  autostart_save_failed: "시작프로그램 설정을 저장하지 못했습니다.",
  autostart_unavailable: "시작프로그램 설정을 확인하지 못했습니다.",
  close_policy_save_failed: "종료 설정을 저장하지 못했습니다. 이전 설정을 유지했습니다.",
  close_policy_unavailable: "종료 설정을 확인하지 못했습니다.",
  component_args_invalid: "요청 형식이 올바르지 않습니다.",
  component_response_invalid: "활동 작업의 결과를 확인하지 못했습니다.",
  digest_busy: "다른 요약 작업을 마친 뒤 다시 시도해 주세요.",
  digest_cancel_timeout: "요약 취소를 확인하지 못했습니다. 잠시 후 상태를 다시 확인해 주세요.",
  digest_cancelled: "요약 만들기를 취소했습니다.",
  digest_handle_expired: "요약 저장 시간이 만료되었습니다. 새로 만들어 주세요.",
  digest_output_invalid: "요약 결과를 확인하지 못했습니다.",
  export_cancelled: "내보내기를 취소했습니다.",
  export_output_invalid: "내보내기 결과를 확인하지 못했습니다.",
  git_invalid_arguments: "Git 조회 조건을 확인해 주세요.",
  git_invalid_target: "Git 프로젝트 경로를 확인해 주세요.",
  git_output_invalid: "Git 조회 결과를 확인하지 못했습니다.",
  git_timeout: "Git 조회 시간이 초과되었습니다.",
  privacy_redaction_failed: "기존 기록에 규칙을 적용하지 못했습니다. 기록은 바뀌지 않았습니다.",
  privacy_rules_invalid: "잘못된 규칙이 있어 저장하지 않았습니다. 표시된 줄을 고쳐 주세요.",
  privacy_rules_save_failed: "개인정보 규칙을 저장하지 못했습니다. 기존 규칙이 유지됩니다.",
  project_probe_failed: "프로젝트 연결을 확인하지 못했습니다.",
  project_settings_unavailable: "프로젝트 설정을 읽거나 저장하지 못했습니다.",
  snapshot_payload_invalid: "연결된 활동 정보를 확인하지 못했습니다.",
  store_busy: "다른 저장소 작업을 마친 뒤 다시 시도해 주세요.",
  tracking_state_unavailable: "활동 수집 상태를 확인하지 못했습니다.",
  tray_unavailable: "트레이를 사용할 수 없어 설정을 변경하지 않았습니다.",
  unavailable: "활동 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
};
