[package]
name = "devbox-manager"
version = "0.3.1"
publish = false
description = "Devbox Manager"
authors = ["jihoon22.lee"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "devbox_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
sha2 = "0.10"
futures-util = "0.3"
devbox-wsl = { package = "wsl", path = "../../../crates/wsl" }
devbox-git = { package = "git", path = "../../../crates/git" }
dirs = "6.0.0"
devbox-filesystem = { package = "filesystem", path = "../../../crates/filesystem" }
