[package]
name = "wsl-desktop"
version = "0.3.3"
publish = false
description = "WSL Desktop"
authors = ["jihoon22.lee"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "wsl_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
portable-pty = "0.9.0"
tokio = { version = "1.53.1", features = ["process"] }
devbox-wsl = { package = "wsl", path = "../../../crates/wsl" }
devbox-applink = { package = "applink", path = "../../../crates/applink" }
dirs = "6.0.0"
devbox-filesystem = { package = "filesystem", path = "../../../crates/filesystem" }

[target.'cfg(windows)'.dependencies]
windows-version = "0.1.7"
