import { MarkdownBody } from "@devbox/markdown-view";
import { useMemo } from "react";
import type { PreviewResponse } from "../types";

interface PreviewPaneProps {
  docPath: string;
  response: PreviewResponse | null;
  error: string | null;
}

/**
 * Preview HTML is already sanitized by crates/markdown.  Mermaid SVG is
 * generated by Mermaid's strict renderer; failed renders retain the last
 * successful SVG for that block and show a small error badge.
 */
export default function PreviewPane({ docPath, response, error }: PreviewPaneProps) {
  const mermaid = useMemo(
    () => (response?.kind === "mermaid" ? [response.source] : (response?.mermaid ?? [])),
    [response],
  );
  const html = response?.kind === "mermaid" ? '<div class="mermaid-block" data-idx="0"></div>' : (response?.html ?? "");

  return (
    <aside className="preview-pane" aria-label="프리뷰">
      <div className="preview-pane-header">
        <span>프리뷰</span>
        <span className="preview-pane-path">{docPath}</span>
      </div>
      {error && (
        <p className="preview-error" role="alert">
          {error}
        </p>
      )}
      {!response ? (
        <p className="preview-empty">렌더링 중...</p>
      ) : (
        <MarkdownBody
          html={html}
          mermaid={mermaid}
          docKey={docPath}
          idPrefix="code-pad-mermaid"
          className="preview-body"
        />
      )}
    </aside>
  );
}
