export interface TreeEntry {
  path: string;
  is_dir: boolean;
}

export interface SearchResult {
  path: string;
  title: string;
}

/** `render_markdown` 커맨드의 응답. Rust `RenderedDoc`과 1:1. */
export interface RenderedDoc {
  title: string | null;
  tags: string[];
  /** 살균 완료된 HTML. mermaid 블록은 placeholder로 치환됨. */
  html: string;
  /** placeholder `data-idx` 순서의 mermaid 원문. */
  mermaid: string[];
}

export type WikilinkStatus = "resolved" | "missing" | "ambiguous" | "invalid";

export interface WikilinkOccurrence {
  target: string;
  label: string;
  line: number;
  column: number;
  /** CodeMirror-compatible UTF-16 offsets. */
  from: number;
  to: number;
  status: WikilinkStatus;
  /** Backend index가 유일하게 해석한 root-relative note path만 들어간다. */
  resolved_path: string | null;
}

export interface WikilinkCandidate {
  path: string;
  title: string;
  /** 자동완성 시 삽입할 root-relative path without `.md`. */
  link_target: string;
}

export interface Backlink {
  source_path: string;
  target: string;
  /** 1-based source position; column uses UTF-16 code units. */
  line: number;
  column: number;
}

export interface ImageAsset {
  /** Knowledge-vault-relative content-hash path returned by native storage. */
  relativePath: string;
  /** Safe Markdown node generated by the native command. */
  markdown: string;
  /** Whether an identical content-hash file was already present. */
  reused: boolean;
}

export interface EditorCursorRequest {
  line: number;
  column: number;
  token: number;
}

export interface QuickCaptureInput {
  title: string;
  body: string;
  tags: string[];
}

export interface QuickCapturePreview {
  /** Opaque native approval slot; never encodes capture content or a path. */
  previewId: string;
  target: string;
  title: string;
  body: string;
  tags: string[];
}

export interface QuickCaptureSaved {
  /** Knowledge-root relative path; an absolute path never crosses IPC. */
  path: string;
}

export type QuickCaptureShortcutState =
  | "registering"
  | "registered"
  | "conflict"
  | "unsupported"
  | "unavailable";

export interface QuickCaptureShortcutStatus {
  shortcut: string;
  state: QuickCaptureShortcutState;
}
