import type { ApiIssue } from "../generated/ApiIssue";
export const apiMessages: Record<ApiIssue, string> = {
  api_workspace_invalid: "작업을 완료하지 못했습니다.",
  api_workspace_project_unavailable: "작업을 완료하지 못했습니다.",
  api_workspace_stale: "작업을 완료하지 못했습니다.",
  api_workspace_unavailable: "작업을 완료하지 못했습니다.",
  component_args_invalid: "작업을 완료하지 못했습니다.",
  component_delivery_busy: "작업을 완료하지 못했습니다.",
  component_delivery_invalid: "작업을 완료하지 못했습니다.",
  component_delivery_unavailable: "작업을 완료하지 못했습니다.",
  component_response_invalid: "작업을 완료하지 못했습니다.",
  component_state_conflict: "작업을 완료하지 못했습니다.",
  component_storage_unavailable: "작업을 완료하지 못했습니다.",
  component_unavailable: "작업을 완료하지 못했습니다.",
  grpc_connect_timeout: "gRPC 연결 또는 reflection 시간이 초과되었습니다.",
  grpc_connection_limit: "열 수 있는 gRPC 연결 수를 초과했습니다.",
  grpc_connection_stale: "gRPC 연결이 닫혔거나 오래되었습니다. 다시 연결하세요.",
  grpc_credential_invalid: "CA와 client certificate/private key 구성을 확인하세요.",
  grpc_credential_storage_failed: "TLS credential을 안전하게 저장하거나 읽지 못했습니다.",
  grpc_credential_storage_unavailable: "TLS credential 저장은 패키징된 Windows 앱에서만 사용할 수 있습니다.",
  grpc_descriptor_invalid: "gRPC descriptor가 올바르지 않거나 허용 범위를 초과했습니다.",
  grpc_export_failed: "gRPC summary를 안전하게 저장하지 못했습니다.",
  grpc_invalid_profile: "endpoint, timeout 또는 TLS 구성을 확인하세요.",
  grpc_method_unavailable: "연결된 descriptor에 선택한 method가 없습니다.",
  grpc_native_required: "gRPC 연결과 native 파일 선택은 데스크톱 앱에서만 사용할 수 있습니다.",
  grpc_protocol_failed: "gRPC transport 또는 응답을 안전하게 처리하지 못했습니다.",
  grpc_reflection_unavailable: "서버 reflection을 사용할 수 없습니다. 서버 설정 또는 local proto를 확인하세요.",
  grpc_request_cancelled: "gRPC 요청을 취소했습니다. 요청은 재시도되지 않았습니다.",
  grpc_request_invalid: "ProtoJSON 입력 형식 또는 message 수를 확인하세요.",
  grpc_request_limit: "이 연결에서 동시에 실행할 수 있는 요청 수를 초과했습니다.",
  grpc_request_timeout: "gRPC deadline이 초과되었습니다. 요청은 재시도되지 않았습니다.",
  grpc_request_too_large: "gRPC 요청이 허용된 크기를 초과했습니다.",
  grpc_response_too_large: "gRPC 응답이 허용된 message 수 또는 크기를 초과했습니다.",
  grpc_source_invalid: "선택한 proto와 import를 안전하게 컴파일하지 못했습니다.",
  grpc_source_selection_invalid: "선택한 proto/import root가 만료되었거나 변경되었습니다. 다시 선택하세요.",
  grpc_source_too_large: "proto source의 파일 수 또는 크기 제한을 초과했습니다.",
  grpc_tls_failed: "TLS 인증서, server name, native root 또는 연결 상태를 확인하세요.",
  knowledge_draft_invalid: "작업을 완료하지 못했습니다.",
  knowledge_owner_invalid: "작업을 완료하지 못했습니다.",
  knowledge_storage_full: "보관함이 가득 찼습니다. 기존 초안을 내보낸 뒤 직접 삭제하고 다시 시도하세요.",
  knowledge_storage_unavailable: "작업을 완료하지 못했습니다.",
  legacy_api_storage_invalid: "작업을 완료하지 못했습니다.",
  mcp_capability_unavailable: "서버가 이 capability를 제공하지 않습니다.",
  mcp_connect_timeout: "MCP 연결 시간이 초과되었습니다.",
  mcp_connection_limit: "열 수 있는 MCP 연결 수를 초과했습니다.",
  mcp_connection_stale: "연결이 닫혔거나 오래되었습니다. 다시 연결하세요.",
  mcp_cursor_invalid: "pagination cursor가 올바르지 않습니다.",
  mcp_invalid_profile: "endpoint, timeout 또는 custom header 구성을 확인하세요.",
  mcp_legacy_fallback: "작업을 완료하지 못했습니다.",
  mcp_legacy_version_negotiated: "작업을 완료하지 못했습니다.",
  mcp_message_invalid: "MCP message 또는 응답 구조가 올바르지 않습니다.",
  mcp_oauth_callback_failed: "OAuth browser callback을 확인하지 못했습니다.",
  mcp_oauth_cancelled: "OAuth authorization을 취소했습니다.",
  mcp_oauth_client_unsupported: "OAuth public client 구성을 지원하지 않습니다.",
  mcp_oauth_discovery_failed: "OAuth 보호 resource 또는 authorization server를 확인하지 못했습니다.",
  mcp_oauth_issuer_mismatch: "OAuth issuer binding이 선택한 issuer와 일치하지 않습니다.",
  mcp_oauth_pkce_required: "OAuth server가 필요한 PKCE S256을 지원하지 않습니다.",
  mcp_oauth_reauthorization_required: "OAuth grant가 만료되어 다시 인증해야 합니다.",
  mcp_oauth_request_invalid: "OAuth 요청 구성을 확인하세요.",
  mcp_oauth_required: "선택한 OAuth grant를 다시 인증하세요.",
  mcp_oauth_resource_mismatch: "OAuth resource binding이 MCP endpoint와 일치하지 않습니다.",
  mcp_oauth_revoke_failed: "OAuth grant를 원격에서 revoke하지 못했습니다. 원하면 로컬에서 제거할 수 있습니다.",
  mcp_oauth_storage_failed: "OAuth grant를 안전하게 저장하거나 읽지 못했습니다.",
  mcp_oauth_token_failed: "OAuth token 교환에 실패했습니다.",
  mcp_redirect_blocked: "credential 보호를 위해 redirect를 차단했습니다.",
  mcp_request_cancelled: "MCP 요청을 취소했습니다.",
  mcp_request_limit: "동시에 실행할 수 있는 MCP 요청 수를 초과했습니다.",
  mcp_request_timeout: "MCP 요청 시간이 초과되었습니다.",
  mcp_request_too_large: "MCP 요청이 허용된 크기를 초과했습니다.",
  mcp_response_too_large: "MCP 응답이 허용된 크기를 초과했습니다.",
  mcp_response_type_invalid: "서버가 JSON 또는 SSE가 아닌 응답을 반환했습니다.",
  mcp_schema_unsupported: "이 tool schema는 안전한 호출 형식으로 해석할 수 없습니다.",
  mcp_secret_unavailable: "현재 Environment의 secret을 안전하게 해제할 수 없습니다.",
  mcp_server_error: "MCP 서버가 JSON-RPC 오류를 반환했습니다.",
  mcp_stdio_cleanup_failed: "native stdio process 정리를 완료하지 못했습니다.",
  mcp_stdio_connection_limit: "열 수 있는 native stdio 연결 수를 초과했습니다.",
  mcp_stdio_connection_stale: "native stdio 연결이 닫혔거나 오래되었습니다. 다시 연결하세요.",
  mcp_stdio_environment_invalid: "stdio environment binding을 확인하세요.",
  mcp_stdio_message_too_large: "native stdio MCP message가 허용된 크기를 초과했습니다.",
  mcp_stdio_profile_invalid: "stdio profile의 executable, 인자, environment 또는 timeout을 확인하세요.",
  mcp_stdio_protocol_invalid: "native stdio MCP message가 올바르지 않습니다.",
  mcp_stdio_request_cancelled: "native stdio MCP 요청을 취소했습니다.",
  mcp_stdio_request_limit: "동시에 실행할 수 있는 native stdio 요청 수를 초과했습니다.",
  mcp_stdio_request_timeout: "native stdio MCP 요청 시간이 초과되었습니다.",
  mcp_stdio_selection_invalid: "선택한 native executable 또는 cwd를 다시 선택하세요.",
  mcp_stdio_spawn_failed: "native executable을 시작하지 못했습니다.",
  mcp_stdio_transport_failed: "native stdio transport 요청에 실패했습니다.",
  mcp_transport_failed: "MCP transport 요청에 실패했습니다.",
  mcp_version_unsupported: "지원하는 MCP protocol version을 협상하지 못했습니다.",
  mock_draft_busy: "작업을 완료하지 못했습니다.",
  mock_draft_expired: "작업을 완료하지 못했습니다.",
  mock_draft_invalid: "작업을 완료하지 못했습니다.",
  mock_draft_unavailable: "작업을 완료하지 못했습니다.",
  native_error_0ffa141e36f0: "WebSocket close code가 올바르지 않습니다",
  native_error_13a4255931ab: "WebSocket 연결을 시작할 수 없습니다",
  native_error_149741b17051: "GraphQL endpoint query에 credential을 넣을 수 없습니다",
  native_error_17a72638b389: "Cookie header와 구조화 Cookie를 동시에 전송할 수 없습니다.",
  native_error_1f76b55d6589: "SSE 요청 본문이 너무 큽니다",
  native_error_252899a04e88: "OpenAPI URL에 연결하지 못했습니다",
  native_error_292b12c17c95: "OpenAPI 문서는 4 MiB 이하만 가져올 수 있습니다",
  native_error_33073648cd6e: "SSE 환경 변수 형식이 올바르지 않습니다",
  native_error_349c6ee3df7f: "SSE 요청 parameter가 너무 깁니다",
  native_error_390b54c32f85: "SSE idle timeout 범위가 올바르지 않습니다",
  native_error_3c1177ccc6e5: "SSE multipart 파일 경로가 너무 깁니다",
  native_error_3c8be37bf5e0: "SSE 인증 설정이 올바르지 않습니다",
  native_error_44dde421c35c: "WebSocket binary payload가 올바르지 않습니다",
  native_error_45c2dd487777: "WebSocket message가 허용된 크기를 초과했습니다",
  native_error_463ac8cf790c: "WebSocket 연결에 실패했습니다",
  native_error_4662419a3d49: "요청이 취소되었습니다",
  native_error_47d5dd07796b: "SSE 요청 항목 수 또는 URL이 제한을 초과했습니다",
  native_error_4a6c32ea00a9: "WebSocket session 상태를 읽을 수 없습니다",
  native_error_4e6d6d3ae546: "SSE 요청 본문 형식이 올바르지 않습니다",
  native_error_4f6139e6d8b2: "Developer Toolbox를 사용할 수 없습니다. 클립보드로 자동 전환하지 않습니다",
  native_error_52a4610ed754: "JSON 파일을 안전하게 처리하지 못했습니다",
  native_error_57dcc8e71e2b: "OpenAPI URL의 안전한 redirect 범위를 벗어났습니다",
  native_error_5953c08a5925: "SSE 환경 변수는 최대 100개까지 사용할 수 있습니다",
  native_error_5a2568ab5822: "SSE 요청 header가 올바르지 않습니다",
  native_error_62c63840f5d9: "Cookie는 최대 100행까지 사용할 수 있습니다.",
  native_error_64e46eeb3623: "SSE 전체 timeout 범위가 올바르지 않습니다",
  native_error_6e4890df1afe: "GraphQL header 크기가 허용된 한계를 초과했습니다",
  native_error_6fe6a4e06bfc: "WebSocket binary를 안전하게 저장할 수 없습니다",
  native_error_700ed54fa2a1: "handoff 저장소를 사용할 수 없습니다",
  native_error_7065d6b493cf: "OpenAPI 문서를 안전하게 읽지 못했습니다",
  native_error_72fc93dbb3bb: "값에 공백, 세미콜론, 따옴표 또는 제어 문자를 사용할 수 없습니다.",
  native_error_78dd672d9aae: "handoff 요청이 다른 작업에서 사용 중입니다. 잠시 후 다시 시도하세요",
  native_error_7af63ead853b: "SSE multipart 파일 전송은 데스크톱 앱에서만 사용할 수 있습니다.",
  native_error_7e5c23216bc5: "SSE 리다이렉트 정책으로 요청을 차단했습니다",
  native_error_809ec96b5769: "SSE 요청 Cookie가 너무 깁니다",
  native_error_82f0b8e19a03: "WebSocket 요청 header가 너무 깁니다",
  native_error_86989f4b8d10: "WebSocket ping을 보낼 수 없습니다",
  native_error_898930572fbb: "GET SSE 요청에는 본문을 사용할 수 없습니다",
  native_error_8b2107214da0: "handoff 요청이 만료되었거나 더 이상 사용할 수 없습니다",
  native_error_8b80c129c169: "WebSocket endpoint URL이 올바르지 않습니다",
  native_error_8f2c5cd08252: "SSE 요청 URL이 너무 깁니다",
  native_error_900c775dc059: "SSE 응답 형식이 아닙니다",
  native_error_9187bbd3128c: "SSE 연결 timeout 범위가 올바르지 않습니다",
  native_error_9464ae2b95a2: "WebSocket endpoint query에 credential을 넣을 수 없습니다",
  native_error_9823300e2dfd: "OpenAPI URL이 성공 응답을 반환하지 않았습니다",
  native_error_9ace2e8957bf: "GraphQL endpoint URL이 올바르지 않습니다",
  native_error_9b450fbd09ea: "SSE 요청을 보낼 수 없습니다",
  native_error_9d044e02e4f2: "SSE 요청 URL이 올바르지 않습니다",
  native_error_a40c623483b7: "SSE multipart part별 Content-Type은 데스크톱 앱에서만 사용할 수 있습니다.",
  native_error_a5d65a7c9ad2: "SSE 요청 항목 수가 제한을 초과했습니다",
  native_error_b535f1f97a14: "Developer Toolbox로 선택 영역을 전달하지 못했습니다. 클립보드로 자동 전환하지 않습니다",
  native_error_ba228492dc19: "WebSocket 연결 시간이 초과되었습니다",
  native_error_be2d74b67a72: "이름이 필요합니다.",
  native_error_bf0590b1cc53: "GraphQL header 행 수가 허용된 한계를 초과했습니다",
  native_error_c2d036e22480: "WebSocket 연결을 닫을 수 없습니다",
  native_error_c5295c1dc259: "WebSocket 인증 설정이 올바르지 않습니다",
  native_error_cad5d5fa7bee: "OpenAPI URL 가져오기 시간이 초과되었습니다",
  native_error_cbf814d599c5: "SSE 인증 설정이 너무 깁니다",
  native_error_cf85b26d9d44: "handoff 미리보기가 만료되었습니다. 다시 전달하세요",
  native_error_d4b6f4fa1184: "WebSocket 요청 header가 올바르지 않습니다",
  native_error_d7f9bc586cd9: "handoff 요청을 사용할 수 없습니다",
  native_error_e1fe1c6953db: "이미 실행 중인 WebSocket 연결이 있습니다",
  native_error_e3207a0b0bb5: "SSE 요청 header가 너무 깁니다",
  native_error_e49092c0ff02: "WebSocket 요청 URL이 너무 깁니다",
  native_error_e4fb51c5a26a: "WebSocket 연결이 열려 있지 않습니다",
  native_error_e60c1973ba50: "binary 응답을 안전하게 저장할 수 없습니다",
  native_error_e8e3aa74c6ca: "WebSocket message를 보낼 수 없습니다",
  native_error_eb904156e3ae: "이름에 Cookie token으로 쓸 수 없는 문자가 있습니다.",
  native_error_ec9552cfa292: "WebSocket close reason이 올바르지 않습니다",
  native_error_f3cfab0036ec: "WebSocket 연결이 끊어졌습니다",
  native_error_f420f083093a: "WebSocket 요청 parameter가 올바르지 않습니다",
  native_error_f65026518d74: "SSE stream은 GET 또는 POST만 지원합니다",
  native_error_fc3030266031: "secret 포함 SSE stream은 데스크톱 앱에서만 사용할 수 있습니다.",
  native_error_fd29f5ca70fe: "WebSocket 연결 timeout 범위가 올바르지 않습니다",
  native_error_fe3411a5d8c8: "WebSocket 요청 항목 수가 제한을 초과했습니다",
  openapi_definition_full: "작업을 완료하지 못했습니다.",
  openapi_definition_invalid: "작업을 완료하지 못했습니다.",
  openapi_definition_unavailable: "작업을 완료하지 못했습니다.",
  owned_worker_assignment_failed: "작업을 완료하지 못했습니다.",
  unavailable: "작업을 완료하지 못했습니다.",
};

import type { WebhookIssue } from "../generated/WebhookIssue";
export const webhookMessages: Record<WebhookIssue, string> = {
  component_args_invalid: "작업을 완료하지 못했습니다.",
  component_closing: "작업을 완료하지 못했습니다.",
  component_response_invalid: "작업을 완료하지 못했습니다.",
  component_state_conflict: "작업을 완료하지 못했습니다.",
  component_state_unavailable: "작업을 완료하지 못했습니다.",
  component_storage_unavailable: "작업을 완료하지 못했습니다.",
  component_unavailable: "작업을 완료하지 못했습니다.",
  lifecycle_hide_unavailable: "작업을 완료하지 못했습니다.",
  lifecycle_settings_changed: "작업을 완료하지 못했습니다.",
  lifecycle_tray_unavailable: "작업을 완료하지 못했습니다.",
  mock_draft_busy: "작업을 완료하지 못했습니다.",
  mock_draft_expired: "작업을 완료하지 못했습니다.",
  mock_draft_invalid: "작업을 완료하지 못했습니다.",
  mock_draft_unavailable: "작업을 완료하지 못했습니다.",
  native_error_066631821755: "서버 bind에 실패했습니다",
  native_error_0c550c94b33e: "겹치는 규칙을 저장하려면 충돌 확인이 필요합니다",
  native_error_0dd534d09121:
    "Log Lens를 사용할 수 없습니다. 설치 또는 업데이트 후 다시 시도하세요. 클립보드로 자동 전환하지 않습니다",
  native_error_16fd76aa4f0f: "fixture 입력이 유효하지 않습니다",
  native_error_1f7d166202fc: "replay 응답을 읽지 못했습니다",
  native_error_22fb1af497e2: "실행 중인 loopback 서버만 Run Manager 서비스로 내보낼 수 있습니다",
  native_error_342b52315581: "규칙 입력이 유효하지 않습니다",
  native_error_446a67110d9d: "API Playground handoff를 만들지 못했습니다. 클립보드로 자동 전환하지 않습니다",
  native_error_495902fcb259: "Logs 연결을 사용할 수 없습니다. 수신 요청과 저장한 fixture는 유지됩니다.",
  native_error_53cc11f43034: "대상 앱 실행 실패 후 handoff를 정리하지 못했습니다. 잠시 후 다시 시도하세요",
  native_error_580bb9625064: "Webhook service profile을 읽을 수 없습니다",
  native_error_59626ff68249: "LAN 공개를 시작하려면 명시적인 확인이 필요합니다",
  native_error_5ad1257b8a81: "Webhook service profile을 만들 수 없습니다",
  native_error_60c27f0116d2: "localhost 서버가 실행 중이 아니거나 주소가 유효하지 않습니다",
  native_error_64e2eeabf510: "replay 입력이 유효하지 않습니다",
  native_error_7148c6ab83dd: "요청 시간이 초과되었습니다",
  native_error_720404dc8aa5: "fixture 저장소가 다른 작업에서 사용 중입니다. 잠시 후 다시 시도하세요",
  native_error_7a45151676e3: "replay 요청이 너무 많습니다. 잠시 후 다시 시도하세요",
  native_error_7b9580926bef: "요청이 너무 많습니다. 잠시 후 다시 시도하세요",
  native_error_7f1146a75ff9: "서버 내부 상태를 읽을 수 없습니다",
  native_error_8043a49376d3: "handoff 요청에 사용할 fixture가 유효하지 않습니다",
  native_error_8c893a1a9859: "response sequence를 초기화하지 못했습니다",
  native_error_974bbe3cd37f: "바이너리 본문 fixture는 API 요청으로 보낼 수 없습니다",
  native_error_9b26c2d9449d: "Workspace Logs에 연결하지 못했습니다. 원본 요청과 fixture는 유지됩니다.",
  native_error_9c743bd82693:
    "API Playground를 실행하지 못했습니다. handoff를 안전하게 정리했으며 클립보드로 자동 전환하지 않습니다",
  native_error_ab70140b4069: "fixture를 찾을 수 없습니다",
  native_error_b115da98ce90: "Webhook service profile 개수 제한에 도달했습니다",
  native_error_b38fea85b6b5: "replay 요청을 보내지 못했습니다",
  native_error_b6737ef0ac28: "credential 형태의 응답이 포함된 규칙은 service profile로 내보낼 수 없습니다",
  native_error_cff919689ee1:
    "Log Lens를 실행하지 못했습니다. handoff를 안전하게 정리했으며 클립보드로 자동 전환하지 않습니다",
  native_error_d4eb3a2200e7:
    "API Playground를 사용할 수 없습니다. 설치 또는 업데이트 후 다시 시도하세요. 클립보드로 자동 전환하지 않습니다",
  native_error_d6437725f788: "Log Lens handoff를 만들지 못했습니다. 클립보드로 자동 전환하지 않습니다",
  native_error_d99e2ca963ed: "fixture 저장소 크기 제한을 초과했습니다",
  native_error_dfa0a355cca6: "fixture 저장소를 저장할 수 없습니다",
  native_error_e453907853a4: "포트는 1~65535 범위여야 합니다",
  native_error_e499457b4657: "요청 헤더가 허용 범위를 초과했습니다",
  native_error_eb088ae5663f: "fixture 저장소가 다른 작업으로 변경되었습니다. 다시 시도하세요",
  native_error_ec1af1045a13: "허용되지 않은 bind 주소입니다",
  native_error_fc8823b89dce: "요청 크기가 허용 범위를 초과했습니다",
  native_error_fd4ee7a85942: "fixture 저장소를 읽을 수 없습니다",
  unavailable: "작업을 완료하지 못했습니다.",
};

import type { ToolboxIssue } from "../generated/ToolboxIssue";
export const transformMessages: Record<ToolboxIssue, string> = {
  component_args_invalid: "작업을 완료하지 못했습니다.",
  component_delivery_busy: "작업을 완료하지 못했습니다.",
  component_delivery_invalid: "작업을 완료하지 못했습니다.",
  component_delivery_unavailable: "작업을 완료하지 못했습니다.",
  component_response_invalid: "작업을 완료하지 못했습니다.",
  component_state_conflict: "작업을 완료하지 못했습니다.",
  component_storage_unavailable: "작업을 완료하지 못했습니다.",
  component_unavailable: "작업을 완료하지 못했습니다.",
  knowledge_draft_invalid: "작업을 완료하지 못했습니다.",
  knowledge_owner_invalid: "작업을 완료하지 못했습니다.",
  knowledge_storage_full: "보관함이 가득 찼습니다. 기존 초안을 내보낸 뒤 직접 삭제하고 다시 시도하세요.",
  knowledge_storage_unavailable: "작업을 완료하지 못했습니다.",
  mock_draft_busy: "작업을 완료하지 못했습니다.",
  mock_draft_expired: "작업을 완료하지 못했습니다.",
  mock_draft_invalid: "작업을 완료하지 못했습니다.",
  mock_draft_unavailable: "작업을 완료하지 못했습니다.",
  native_error_103a413e24f8: "JWT 검증을 처리할 수 없습니다.",
  native_error_184e42b0f97c: "QR 이미지를 생성하지 못했습니다.",
  native_error_20f163616a48: "QR 여백이 올바르지 않습니다.",
  native_error_2931063733d3: "QR 입력은 비어 있을 수 없습니다.",
  native_error_2e177f197f6b: "QR 입력 형식이 올바르지 않습니다.",
  native_error_446a67110d9d: "API Playground handoff를 만들지 못했습니다. 클립보드로 자동 전환하지 않습니다",
  native_error_4b8f3c1e2449: "QR 용량을 초과했습니다. 버전 또는 오류 보정 수준을 조정하세요.",
  native_error_5c4537feee0e: "암호학적으로 안전한 난수를 사용할 수 없습니다.",
  native_error_7b47bde22cd3: "QR 버전이 올바르지 않습니다.",
  native_error_84f3635651e5:
    "Knowledge를 사용할 수 없습니다. 설치 또는 업데이트 후 다시 시도하세요. 클립보드로 자동 전환하지 않습니다",
  native_error_880caf8288ea: "Wi-Fi 설정이 올바르지 않습니다.",
  native_error_8eb0326aefbb: "HMAC 입력을 처리할 수 없습니다.",
  native_error_95913153dce4: "Knowledge draft를 만들거나 전달하지 못했습니다. 클립보드로 자동 전환하지 않습니다",
  native_error_a22e2614df1f: "QR 오류 보정 수준이 올바르지 않습니다.",
  native_error_a34bb1ec3d7c: "식별자 생성 순서를 유지할 수 없습니다.",
  native_error_b3c273a8111a: "QR 크기가 버전과 여백에 비해 작습니다.",
  native_error_b6af3f8c3364: "QR 입력이 너무 깁니다.",
  native_error_c9a8491603aa: "QR 크기가 올바르지 않습니다.",
  native_error_d265251361e9: "Toolbox workflow metadata를 저장할 수 없습니다.",
  native_error_d4eb3a2200e7:
    "API Playground를 사용할 수 없습니다. 설치 또는 업데이트 후 다시 시도하세요. 클립보드로 자동 전환하지 않습니다",
  native_error_dd5ec2c72ee5: "API Playground로 전달할 텍스트가 유효하지 않습니다",
  native_error_e5ef35a5a0cf:
    "API Playground를 실행하지 못했습니다. 전달 데이터는 폐기했습니다. 클립보드로 자동 전환하지 않습니다",
  transform_export_denied: "작업을 완료하지 못했습니다.",
  unavailable: "작업을 완료하지 못했습니다.",
};
