import { StrictMode } from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { ApiWorkspacePanel } from "./ApiWorkspace";
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));
vi.mock("../transport", () => ({ componentInvoke: () => invoke }));
vi.mock("./lib/isTauri", () => ({ isTauri: () => true }));
const id = "a2345678-1234-4234-8234-123456789abc";
const links = { collectionIds: ["c1"], environmentIds: ["e1"], openApiDefinitionIds: [], mockProfileIds: [] };
const workspace = { id, name: "Fixture", projectId: null, links };
const doc = { schemaVersion: 1, revision: 3, selectedId: null, workspaces: [workspace] };
const state = { document: doc, currentProjectId: null, mockProfiles: [] };
const props = { collections: [{ id: "c1", name: "Collection A" }], environments: [{ id: "e1", name: "Environment A" }] };
afterEach(cleanup);
beforeEach(() => { invoke.mockReset(); invoke.mockResolvedValue(state); });
it("loads the selected metadata in StrictMode and switches with its current revision only", async () => {
  const onChange = vi.fn(); render(<StrictMode><ApiWorkspacePanel {...props} onChange={onChange} /></StrictMode>);
  await waitFor(() => expect((screen.getByRole("combobox", { name: "API Workspace 선택" }) as HTMLSelectElement).disabled).toBe(false));
  invoke.mockResolvedValueOnce({ ...doc, revision: 4, selectedId: id });
  fireEvent.change(screen.getByRole("combobox", { name: "API Workspace 선택" }), { target: { value: id } });
  await waitFor(() => expect(onChange).toHaveBeenLastCalledWith(workspace));
  expect(invoke).toHaveBeenLastCalledWith("select_api_workspace", { expectedRevision: 3, id });
  expect(invoke.mock.calls.every(([method]) => ["api_workspace_state", "select_api_workspace"].includes(method))).toBe(true);
  expect(screen.getByText(/요청 초안·현재 환경·연결은 유지됩니다/)).not.toBeNull();
});
it("keeps unsaved metadata after a stale save and cannot invent a project binding", async () => {
  render(<ApiWorkspacePanel {...props} onChange={vi.fn()} />);
  await waitFor(() => expect((screen.getByRole("button", { name: "새 Workspace" }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole("button", { name: "새 Workspace" }));
  fireEvent.change(screen.getByRole("textbox", { name: "Workspace 이름" }), { target: { value: "My Workspace" } });
  expect((screen.getByRole("option", { name: "현재 Project (연결 없음)" }) as HTMLOptionElement).disabled).toBe(true);
  fireEvent.click(screen.getByRole("checkbox", { name: "Collection A" }));
  invoke.mockRejectedValueOnce(new Error("api_workspace_stale"));
  fireEvent.click(screen.getByRole("button", { name: "연결 저장" }));
  expect((await screen.findByRole("alert")).textContent).toContain("초안은 유지됩니다");
  expect((screen.getByRole("textbox", { name: "Workspace 이름" }) as HTMLInputElement).value).toBe("My Workspace");
  expect(invoke).toHaveBeenLastCalledWith("save_api_workspace", expect.objectContaining({ expectedRevision: 3, association: "standalone", links: { ...links, environmentIds: [] } }));
});
it("deletes only after explicit confirmation and emits the native remaining selection", async () => {
  invoke.mockResolvedValueOnce({ ...state, document: { ...doc, selectedId: id } });
  const onChange = vi.fn(); render(<ApiWorkspacePanel {...props} onChange={onChange} />);
  fireEvent.click(await screen.findByRole("button", { name: "Workspace 삭제…" }));
  expect(invoke).toHaveBeenCalledTimes(1);
  invoke.mockResolvedValueOnce({ ...doc, revision: 4, workspaces: [] });
  fireEvent.click(screen.getByRole("button", { name: "Workspace 삭제 확인" }));
  await waitFor(() => expect(onChange).toHaveBeenLastCalledWith(null));
  expect(invoke).toHaveBeenLastCalledWith("delete_api_workspace", { expectedRevision: 3, id });
});
it("ignores a late native selection after the panel unmounts", async () => {
  let resolve!: (value: unknown) => void;
  invoke.mockImplementationOnce(() => new Promise(done => { resolve = done; }));
  const onChange = vi.fn(); const view = render(<ApiWorkspacePanel {...props} onChange={onChange} />); view.unmount();
  await act(async () => resolve(state)); expect(onChange).not.toHaveBeenCalled();
});
