[package]
name = "repo-manager"
version = "0.1.1"
description = "Git Worktree Manager"
authors = ["jihoon22.lee"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "repo_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
devbox-wsl = { package = "wsl", path = "../../../crates/wsl" }
devbox-launch = { package = "launch", path = "../../../crates/launch" }
devbox-git = { package = "git", path = "../../../crates/git" }
devbox-filesystem = { package = "filesystem", path = "../../../crates/filesystem" }

[dev-dependencies]
tempfile = "3"

