//! Bounded, local-only captured-request replay.
//!
//! Replay is deliberately a small HTTP/1.1 client rather than a general URL
//! fetcher.  Its destination is derived from the currently running listener,
//! only loopback bind addresses are accepted, and the source must already be
//! a validated masked fixture.  No response body is returned to the command
//! layer; the status code is enough for the user to confirm the local rule.

use super::fixtures::{validate_fixture, CapturedFixture};
use super::history::{MAX_BODY_BYTES, MAX_HEADERS, MAX_HEADER_BYTES, MAX_HEADER_CHARS};
use std::collections::VecDeque;
use std::fmt::Write as FmtWrite;
use std::io::{self, Read, Write};
use std::net::{Ipv4Addr, Ipv6Addr, SocketAddr, TcpStream};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};

pub const MAX_REPLAY_BODY_BYTES: usize = MAX_BODY_BYTES;
/// Three headers are always generated by the native client (`Host`,
/// `Content-Length`, and `Connection`). Reserve those slots so the resulting
/// request still passes the listener's aggregate header admission instead of
/// accepting a fixture that can only replay into a guaranteed `431`.
pub const MAX_REPLAY_HEADERS: usize = MAX_HEADERS.saturating_sub(3);
pub const MAX_REPLAY_HEADER_CHARS: usize = MAX_HEADER_CHARS;
pub const MAX_REPLAY_HEADER_BYTES: usize = MAX_HEADER_BYTES;
/// A replay reads only enough bytes to parse the status line and headers.  A
/// response body is intentionally never retained in the replay result.
pub const MAX_REPLAY_RESPONSE_HEADER_BYTES: usize = 64 * 1024;
pub const REPLAY_CONNECT_TIMEOUT_MS: u64 = 2_000;
pub const REPLAY_READ_TIMEOUT_MS: u64 = 2_000;
/// The read timeout is an idle timeout; this separate wall-clock bound keeps
/// a peer that sends one byte just before every idle deadline from retaining
/// a replay worker forever.
pub const REPLAY_TOTAL_TIMEOUT_MS: u64 = 5_000;
/// The UI sends one request per action, but a process-local limiter also
/// protects callers that invoke the command directly or in a tight loop.
pub const MAX_REPLAYS_PER_WINDOW: usize = 20;
pub const REPLAY_RATE_WINDOW_MS: i64 = 1_000;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReplayError {
    InvalidFixture,
    InvalidTarget,
    TooLarge,
    Cancelled,
    Network,
    InvalidResponse,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReplayRequest {
    pub method: String,
    pub target: String,
    pub headers: Vec<(String, String)>,
    pub body: String,
}

impl ReplayRequest {
    /// Encode a complete request after all fields have crossed validation.
    /// This method is kept private to the native client so arbitrary wire
    /// bytes cannot be supplied by an IPC caller.
    fn wire_bytes(&self) -> Vec<u8> {
        let mut head = String::with_capacity(
            self.method.len()
                + self.target.len()
                + self
                    .headers
                    .iter()
                    .map(|(name, value)| name.len() + value.len() + 4)
                    .sum::<usize>()
                + 64,
        );
        // All fields are validated before this method is called, so the
        // formatting operations cannot fail for allocation or UTF-8 reasons.
        let _ = write!(&mut head, "{} {} HTTP/1.1\r\n", self.method, self.target);
        for (name, value) in &self.headers {
            let _ = write!(&mut head, "{name}: {value}\r\n");
        }
        head.push_str("\r\n");
        let mut bytes = head.into_bytes();
        bytes.extend_from_slice(self.body.as_bytes());
        bytes
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReplayResponse {
    pub status: u16,
}

#[derive(Debug, Default)]
pub struct ReplayRateLimiter {
    events: VecDeque<i64>,
}

impl ReplayRateLimiter {
    pub fn allow(&mut self, now_ms: i64) -> bool {
        // A backwards wall-clock correction starts a fresh bounded window;
        // it never leaves the action permanently locked out.
        if self.events.back().is_some_and(|latest| now_ms < *latest) {
            self.events.clear();
        }
        while self
            .events
            .front()
            .is_some_and(|oldest| now_ms.saturating_sub(*oldest) >= REPLAY_RATE_WINDOW_MS)
        {
            self.events.pop_front();
        }
        if self.events.len() >= MAX_REPLAYS_PER_WINDOW {
            return false;
        }
        self.events.push_back(now_ms);
        true
    }
}

fn split_address(address: &str) -> Option<(&str, &str)> {
    if address.starts_with('[') {
        let close = address.find(']')?;
        let host = &address[1..close];
        let port = address.get(close + 1..)?.strip_prefix(':')?;
        Some((host, port))
    } else {
        address.rsplit_once(':')
    }
}

/// Parse only addresses the app itself can produce and map wildcard binds to
/// their loopback destination.  There is intentionally no DNS resolution.
pub fn loopback_socket(address: &str) -> Result<SocketAddr, ReplayError> {
    if address.is_empty() || address.chars().count() > 128 || address != address.trim() {
        return Err(ReplayError::InvalidTarget);
    }
    let (host, port) = split_address(address).ok_or(ReplayError::InvalidTarget)?;
    let port = port
        .parse::<u16>()
        .ok()
        .filter(|port| *port != 0)
        .ok_or(ReplayError::InvalidTarget)?;
    match host.to_ascii_lowercase().as_str() {
        "127.0.0.1" | "localhost" | "0.0.0.0" => Ok(SocketAddr::from((Ipv4Addr::LOCALHOST, port))),
        "::1" | "[::1]" | "0:0:0:0:0:0:0:1" | "::" => {
            Ok(SocketAddr::from((Ipv6Addr::LOCALHOST, port)))
        }
        _ => Err(ReplayError::InvalidTarget),
    }
}

fn forbidden_header(name: &str) -> bool {
    matches!(
        name.to_ascii_lowercase().as_str(),
        "connection"
            | "content-length"
            | "expect"
            | "host"
            | "proxy-connection"
            | "te"
            | "trailer"
            | "transfer-encoding"
            | "upgrade"
    )
}

/// Build a request from a previously sanitized fixture.  Sensitive values in
/// the fixture are already `[REDACTED]`; this function never receives raw
/// history headers or a frontend-provided body.
pub fn build_request(
    fixture: &CapturedFixture,
    server_address: &str,
) -> Result<(SocketAddr, ReplayRequest), ReplayError> {
    validate_fixture(fixture).map_err(|_| ReplayError::InvalidFixture)?;
    // The native client writes an HTTP/1.1 request directly.  Header fields
    // and request-targets are therefore required to remain ASCII; accepting
    // arbitrary UTF-8 here would produce bytes that the native parser (and
    // many real webhook receivers) cannot parse consistently.
    if !fixture.method.is_ascii()
        || !fixture.url.is_ascii()
        || fixture
            .headers
            .iter()
            .any(|(name, value)| !name.is_ascii() || !value.is_ascii())
    {
        return Err(ReplayError::InvalidFixture);
    }
    let destination = loopback_socket(server_address)?;
    if fixture.body.len() > MAX_REPLAY_BODY_BYTES {
        return Err(ReplayError::TooLarge);
    }
    if fixture.headers.len() > MAX_REPLAY_HEADERS {
        return Err(ReplayError::TooLarge);
    }

    let mut headers = Vec::with_capacity(fixture.headers.len() + 3);
    headers.push(("Host".to_string(), "localhost".to_string()));
    for (name, value) in &fixture.headers {
        if forbidden_header(name) {
            continue;
        }
        headers.push((name.clone(), value.clone()));
    }
    headers.push(("Content-Length".to_string(), fixture.body.len().to_string()));
    headers.push(("Connection".to_string(), "close".to_string()));

    // `validate_fixture` bounds the source, while this second check includes
    // the generated transport headers.  The listener applies the same
    // aggregate budget to the complete wire request, so a fixture near the
    // source limit must fail closed rather than replaying into a guaranteed
    // `431` response.
    if headers.len() > MAX_HEADERS
        || headers
            .iter()
            .map(|(name, value)| name.chars().count() + value.chars().count())
            .sum::<usize>()
            > MAX_REPLAY_HEADER_CHARS
        || headers
            .iter()
            .map(|(name, value)| name.len() + value.len())
            .sum::<usize>()
            > MAX_REPLAY_HEADER_BYTES
    {
        return Err(ReplayError::TooLarge);
    }

    Ok((
        destination,
        ReplayRequest {
            method: fixture.method.clone(),
            target: fixture.url.clone(),
            headers,
            body: fixture.body.clone(),
        },
    ))
}

pub fn send(
    fixture: &CapturedFixture,
    server_address: &str,
    cancel: &AtomicBool,
) -> Result<ReplayResponse, ReplayError> {
    if cancel.load(Ordering::Acquire) {
        return Err(ReplayError::Cancelled);
    }
    let (destination, request) = build_request(fixture, server_address)?;
    let connect_timeout = Duration::from_millis(REPLAY_CONNECT_TIMEOUT_MS);
    let mut stream = TcpStream::connect_timeout(&destination, connect_timeout)
        .map_err(|_| ReplayError::Network)?;
    let deadline = Instant::now() + Duration::from_millis(REPLAY_TOTAL_TIMEOUT_MS);
    write_request(
        &mut stream,
        &request.wire_bytes(),
        deadline,
        connect_timeout,
        cancel,
    )?;
    read_response_status(&mut stream, deadline, cancel)
}

fn timeout_until(deadline: Instant, ceiling: Duration) -> Result<Duration, ReplayError> {
    let remaining = deadline.saturating_duration_since(Instant::now());
    if remaining.is_zero() {
        return Err(ReplayError::Network);
    }
    Ok(remaining.min(ceiling))
}

fn write_request(
    stream: &mut TcpStream,
    bytes: &[u8],
    deadline: Instant,
    idle_timeout: Duration,
    cancel: &AtomicBool,
) -> Result<(), ReplayError> {
    let mut offset = 0usize;
    while offset < bytes.len() {
        if cancel.load(Ordering::Acquire) {
            return Err(ReplayError::Cancelled);
        }
        stream
            .set_write_timeout(Some(timeout_until(deadline, idle_timeout)?))
            .map_err(|_| ReplayError::Network)?;
        let written = stream
            .write(&bytes[offset..])
            .map_err(|_| ReplayError::Network)?;
        if written == 0 {
            return Err(ReplayError::Network);
        }
        offset += written;
    }
    Ok(())
}

fn header_end(bytes: &[u8]) -> Option<usize> {
    bytes.windows(4).position(|window| window == b"\r\n\r\n")
}

fn read_response_status(
    stream: &mut TcpStream,
    deadline: Instant,
    cancel: &AtomicBool,
) -> Result<ReplayResponse, ReplayError> {
    let mut bytes = Vec::with_capacity(4096);
    let mut chunk = [0u8; 4096];
    loop {
        if cancel.load(Ordering::Acquire) {
            return Err(ReplayError::Cancelled);
        }
        if bytes.len() >= MAX_REPLAY_RESPONSE_HEADER_BYTES {
            return Err(ReplayError::InvalidResponse);
        }
        stream
            .set_read_timeout(Some(timeout_until(
                deadline,
                Duration::from_millis(REPLAY_READ_TIMEOUT_MS),
            )?))
            .map_err(|_| ReplayError::Network)?;
        let read = stream
            .read(&mut chunk)
            .map_err(|error| match error.kind() {
                io::ErrorKind::TimedOut | io::ErrorKind::WouldBlock => ReplayError::Network,
                _ => ReplayError::Network,
            })?;
        if read == 0 {
            return Err(ReplayError::InvalidResponse);
        }
        let remaining = MAX_REPLAY_RESPONSE_HEADER_BYTES - bytes.len();
        bytes.extend_from_slice(&chunk[..read.min(remaining)]);
        let Some(end) = header_end(&bytes) else {
            continue;
        };
        let line_end = bytes[..end]
            .windows(2)
            .position(|window| window == b"\r\n")
            .ok_or(ReplayError::InvalidResponse)?;
        let line =
            std::str::from_utf8(&bytes[..line_end]).map_err(|_| ReplayError::InvalidResponse)?;
        let mut fields = line.splitn(3, ' ');
        let version = fields.next().ok_or(ReplayError::InvalidResponse)?;
        let status = fields
            .next()
            .filter(|code| code.len() == 3 && code.bytes().all(|byte| byte.is_ascii_digit()))
            .and_then(|code| code.parse::<u16>().ok())
            .filter(|status| (100..=599).contains(status))
            .ok_or(ReplayError::InvalidResponse)?;
        // The local listener emits only HTTP/1.0 or HTTP/1.1.  Accepting an
        // arbitrary `HTTP/1.*` token would make a malformed/intercepted
        // response look valid and could disagree with downstream framing
        // parsers.
        if !matches!(version, "HTTP/1.0" | "HTTP/1.1") {
            return Err(ReplayError::InvalidResponse);
        }
        return Ok(ReplayResponse { status });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::TcpListener;
    use std::thread;

    fn fixture() -> CapturedFixture {
        CapturedFixture {
            id: "fixture-1".into(),
            method: "POST".into(),
            url: "/hooks/push?event=created".into(),
            headers: vec![
                ("Authorization".into(), "[REDACTED]".into()),
                ("Content-Type".into(), "application/json".into()),
                ("Host".into(), "attacker.invalid".into()),
                ("Content-Length".into(), "999999".into()),
            ],
            body: r#"{"event":"push","token":"[REDACTED]"}"#.into(),
            received_at_ms: 1,
        }
    }

    #[test]
    fn loopback_target_never_resolves_remote_hosts() {
        assert_eq!(
            loopback_socket("127.0.0.1:9000").unwrap(),
            SocketAddr::from((Ipv4Addr::LOCALHOST, 9000))
        );
        assert_eq!(
            loopback_socket("0.0.0.0:9000").unwrap(),
            SocketAddr::from((Ipv4Addr::LOCALHOST, 9000))
        );
        assert_eq!(
            loopback_socket("[::]:9000").unwrap(),
            SocketAddr::from((Ipv6Addr::LOCALHOST, 9000))
        );
        // `start_server` historically rendered ::1 as `::1:port`; accept
        // that app-owned form without opening a general IPv6 parser.
        assert_eq!(
            loopback_socket("::1:9000").unwrap(),
            SocketAddr::from((Ipv6Addr::LOCALHOST, 9000))
        );
        assert!(matches!(
            loopback_socket("192.168.0.5:9000"),
            Err(ReplayError::InvalidTarget)
        ));
        assert!(matches!(
            loopback_socket("example.invalid:9000"),
            Err(ReplayError::InvalidTarget)
        ));
    }

    #[test]
    fn request_uses_masked_snapshot_and_owns_transport_headers() {
        let (_, request) = build_request(&fixture(), "127.0.0.1:9000").unwrap();
        let wire = String::from_utf8(request.wire_bytes()).unwrap();
        assert!(wire.starts_with("POST /hooks/push?event=created HTTP/1.1\r\n"));
        assert!(wire.contains("Authorization: [REDACTED]\r\n"));
        assert!(wire.contains("Host: localhost\r\n"));
        assert!(wire.contains("Content-Length: 37\r\n"));
        assert!(wire.contains("Connection: close\r\n"));
        assert!(!wire.contains("attacker.invalid"));
        assert!(!wire.contains("999999"));
        assert!(!wire.contains("raw-secret"));
    }

    #[test]
    fn invalid_and_oversized_fixture_inputs_fail_closed() {
        let mut invalid = fixture();
        invalid.url = "https://external.invalid/hook".into();
        assert_eq!(
            build_request(&invalid, "127.0.0.1:9000"),
            Err(ReplayError::InvalidFixture)
        );

        invalid = fixture();
        invalid.headers[1].1 = "한글 헤더 값".into();
        assert_eq!(
            build_request(&invalid, "127.0.0.1:9000"),
            Err(ReplayError::InvalidFixture)
        );

        invalid = fixture();
        invalid.url = "/hooks/한글".into();
        assert_eq!(
            build_request(&invalid, "127.0.0.1:9000"),
            Err(ReplayError::InvalidFixture)
        );

        let mut oversized = fixture();
        oversized.body = "x".repeat(MAX_REPLAY_BODY_BYTES + 1);
        assert_eq!(
            build_request(&oversized, "127.0.0.1:9000"),
            Err(ReplayError::InvalidFixture)
        );
    }

    #[test]
    fn replay_reserves_listener_header_budget_for_generated_transport_fields() {
        let mut too_many_headers = fixture();
        too_many_headers.headers = (0..=MAX_REPLAY_HEADERS)
            .map(|index| (format!("X-Test-{index}"), "ok".to_string()))
            .collect();
        assert_eq!(
            build_request(&too_many_headers, "127.0.0.1:9000"),
            Err(ReplayError::TooLarge)
        );

        let mut too_many_bytes = fixture();
        too_many_bytes.headers = (0..16)
            .map(|index| (format!("X{index}"), "x".repeat(3_997)))
            .collect();
        assert_eq!(
            build_request(&too_many_bytes, "127.0.0.1:9000"),
            Err(ReplayError::TooLarge)
        );
    }

    #[test]
    fn replay_rate_limit_is_bounded_and_recovers_after_a_window() {
        let mut limiter = ReplayRateLimiter::default();
        for _ in 0..MAX_REPLAYS_PER_WINDOW {
            assert!(limiter.allow(10));
        }
        assert!(!limiter.allow(10));
        assert!(limiter.allow(REPLAY_RATE_WINDOW_MS + 10));
    }

    #[test]
    fn cancelled_replay_never_connects_or_consumes_network_time() {
        let cancel = AtomicBool::new(true);
        assert_eq!(
            send(&fixture(), "127.0.0.1:1", &cancel),
            Err(ReplayError::Cancelled)
        );
    }

    #[test]
    fn native_send_uses_loopback_and_returns_status_without_response_body() {
        let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
        let address = listener.local_addr().unwrap().to_string();
        let server = thread::spawn(move || {
            let (mut stream, _) = listener.accept().unwrap();
            let mut request = Vec::new();
            let mut byte = [0u8; 1];
            while !request.ends_with(b"\r\n\r\n") && request.len() < 64 * 1024 {
                stream.read_exact(&mut byte).unwrap();
                request.push(byte[0]);
            }
            let request = String::from_utf8(request).unwrap();
            assert!(request.starts_with("POST /hooks/push?event=created HTTP/1.1\r\n"));
            assert!(request.contains("Authorization: [REDACTED]\r\n"));
            assert!(!request.contains("attacker.invalid"));
            assert!(!request.contains("raw-secret"));
            stream
                .write_all(
                    b"HTTP/1.1 503 Service Unavailable\r\nContent-Length: 19\r\nConnection: close\r\n\r\nraw response secret",
                )
                .unwrap();
        });

        let cancel = AtomicBool::new(false);
        let result = send(&fixture(), &address, &cancel).unwrap();
        assert_eq!(result, ReplayResponse { status: 503 });
        server.join().unwrap();
    }
}
