[package]
name = "devbox-agent"
version = "0.8.1"
publish = false
edition = "2021"
description = "Devbox installed Suite background component"

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
tauri-plugin-single-instance = "2"
product-shell-tauri = { path = "../../crates/product-shell-tauri" }
agent-protocol = { path = "../../crates/agent-protocol" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
suite-runtime = { path = "../../crates/suite-runtime" }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }
