//! Wire observations, not a scheduler. Native owners retain cancellation and
//! worker lifetime; dropping a view never implies that its operation stopped.
use crate::Provenance;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum ProblemCode {
    Unauthorized,
    InvalidRequest,
    Expired,
    Replayed,
    Overloaded,
    StaleContext,
    Unavailable,
}

/// Codes carry no native paths, request bodies or OS error strings. Provenance
/// is generated by the native owner; it does not confer permission to retry.
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Problem {
    pub code: ProblemCode,
    pub provenance: Provenance,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(tag = "state", rename_all = "kebab-case", deny_unknown_fields)]
pub enum OperationState {
    Running {},
    Succeeded {},
    Cancelled {},
    Stale {},
    Failed { code: ProblemCode },
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Operation {
    pub provenance: Provenance,
    pub outcome: OperationState,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shared_observations_keep_failure_cancellation_and_staleness_distinct() {
        let values: Vec<Operation> = serde_json::from_str(include_str!(
            "../../../packages/product-shell/fixtures/operations.json"
        ))
        .unwrap();
        assert_eq!(values.len(), 6);
        assert_eq!(values[2].outcome, OperationState::Cancelled {});
        assert_eq!(values[3].outcome, OperationState::Stale {});
        assert_eq!(
            values[4].outcome,
            OperationState::Failed {
                code: ProblemCode::Expired
            }
        );
        for bad in [
            r#"{"state":"failed"}"#,
            r#"{"state":"succeeded","code":"expired"}"#,
            r#"{"state":"failed","code":"future"}"#,
            r#"{"state":"running","path":"private"}"#,
        ] {
            assert!(serde_json::from_str::<OperationState>(bad).is_err());
        }
    }
}
