import type { ToolsIssue } from "./generated/ToolsIssue";
export const toolsMessages: Record<ToolsIssue, string> = {
  manager_args_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  manager_method_denied: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  manager_response_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  manager_state_conflict: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  manager_url_denied: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  manager_url_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
};
import type { DeliveryIssue } from "./generated/DeliveryIssue";
export const deliveryMessages: Record<DeliveryIssue, string> = {
  bootstrap_arguments_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_clock_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_data_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_data_unsafe: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_dispatcher_untrusted: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_gate_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_gate_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_gate_unsafe: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_helper_busy: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_identity_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_journal_missing: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_launch_failed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_owner_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_owner_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_payload_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_payload_incomplete: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_restore_retention_review_required: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_root_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_root_unsafe: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_store_preparation_required: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  bootstrap_update_pending: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  checkpoint_missing: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  downgrade_requires_backup_export: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  installation_folder_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  inventory_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  inventory_worker_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  manager_tools_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_action_already_started: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_action_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_operation_conflict: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_operation_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_operation_unsafe: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_plan_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_plan_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_record_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_record_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  restore_worker_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_health_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_health_required: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_journal_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_journal_missing: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_journal_stale: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_owner_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_owner_expired: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_owner_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_owner_phase_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_space_insufficient: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_store_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_windows_required: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  suite_writers_must_close: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_activation_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_already_installed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_already_launched: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_asset_changed: "다운로드한 파일의 크기 또는 해시가 공식 배포 정보와 다릅니다. 실행하지 않았습니다.",
  update_asset_missing: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_asset_topology_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_busy: "진행 중인 업데이트 요청이 있습니다.",
  update_cache_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_cache_conflict: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_cache_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_cache_unsafe: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_caller_untrusted: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_claim_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_claim_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_clock_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_commit_started: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_committed_installation_required: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_download_cancelled: "다운로드를 취소했습니다.",
  update_download_failed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_download_large: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_download_required: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_installed_suite_required:
    "설치형 Suite에서 업데이트할 수 있습니다. 독립 portable는 새 ZIP을 별도 폴더에서 검토하세요.",
  update_journal_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_launch_failed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_manifest_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_manifest_digest_missing: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_manifest_missing: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_network_timeout: "릴리스 확인 시간이 초과되었습니다.",
  update_network_unavailable: "공식 릴리스 서버에 연결하지 못했습니다.",
  update_operation_conflict: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_operation_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_other_generation_pending: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_other_recovery_pending: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_owner_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_owner_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_plan_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_plan_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_previous_operation_incomplete: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_progress_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_record_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_record_write_failed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_records_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_release_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_request_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_resume_selected_action: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_retention_review_required: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_review_expired: "업데이트 정보를 다시 확인하세요.",
  update_review_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_revision_exhausted: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_root_changed: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_store_unavailable: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
  update_version_invalid: "작업을 완료하지 못했습니다. 현재 상태와 검토한 대상을 확인해 주세요.",
};
