import type { SetupIssue } from "../generated/SetupIssue";
export const setupMessages: Record<SetupIssue, string> = {
  cancelled: "작업을 취소했습니다.",
  component_args_invalid: "요청을 확인해 주세요.",
  component_initialization_failed: "저장소 초기화를 완료하지 못했습니다. 앱을 다시 시작해 주세요.",
  component_response_invalid: "저장소 설정 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  component_state_conflict: "저장소 초기화를 완료하지 못했습니다. 앱을 다시 시작해 주세요.",
  future_schema: "더 최신 버전의 저장소입니다. 원본을 유지했습니다.",
  import_restart_required: "현재 노트를 저장하고 앱을 다시 시작한 뒤 가져오기를 진행해 주세요.",
  restart_required: "저장소 초기화를 완료하지 못했습니다. 앱을 다시 시작해 주세요.",
  setup_required: "저장소를 먼저 준비해 주세요.",
  store_busy: "다른 작업을 마친 뒤 다시 시도해 주세요.",
  store_future_schema: "더 최신 버전의 저장소입니다. 원본을 유지했습니다.",
  store_invalid: "저장소 정보를 확인할 수 없습니다. 기존 데이터는 유지됩니다.",
  store_manifest_invalid: "저장소 정보를 확인할 수 없습니다. 기존 데이터는 유지됩니다.",
  store_path_invalid: "저장소 정보를 확인할 수 없습니다. 기존 데이터는 유지됩니다.",
  store_unavailable: "저장소 설정 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  unavailable: "저장소 설정 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  vault_binding_invalid: "저장소 연결을 확인할 수 없습니다. 현재 저장소를 유지했습니다.",
  vault_binding_unavailable: "저장소 연결을 확인할 수 없습니다. 현재 저장소를 유지했습니다.",
  vault_change_cancelled: "작업을 취소했습니다.",
  vault_change_conflict: "예약한 가져오기 또는 저장소 변경을 먼저 마치거나 취소해 주세요.",
  vault_change_future: "더 최신 버전의 저장소입니다. 원본을 유지했습니다.",
  vault_change_invalid: "저장소 변경 정보를 확인할 수 없습니다. 현재 연결과 원본 파일은 유지됩니다.",
  vault_change_same: "이미 사용하고 있는 노트 폴더입니다.",
  vault_change_save_failed: "저장소 연결을 저장하지 못했습니다. 공간과 권한을 확인하고 다시 시도해 주세요.",
  vault_change_stale: "폴더나 연결 정보가 바뀌었거나 미리보기가 만료되었습니다. 다시 확인해 주세요.",
  vault_change_timeout: "폴더 확인이 제한 시간을 넘었습니다. 변경을 취소하고 현재 저장소로 계속할 수 있습니다.",
  vault_owner_busy: "다른 Knowledge 설치가 이 노트 저장소를 사용 중입니다. 해당 앱을 종료한 뒤 다시 시도해 주세요.",
  vault_owner_unavailable: "저장소 연결을 확인할 수 없습니다. 현재 저장소를 유지했습니다.",
};
