[package]
name = "api-protocols"
version = "0.1.0"
publish = false
edition = "2021"
description = "Shared API protocol validation and codecs"

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
getrandom = { workspace = true }
prost = { workspace = true }
prost-reflect = { workspace = true }
protox = "0.9.1"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tonic = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }
devbox-filesystem = { package = "filesystem", path = "../filesystem" }

[dev-dependencies]
tempfile = { workspace = true }
