[package]
name = "devbox-control-center"
default-run = "devbox-control-center"
version = "0.8.1"
publish = false
edition = "2021"
authors = ["jihoon22.lee"]
description = "Devbox Control Center development product shell"

[lib]
name = "devbox_control_center_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
suite-runtime = { path = "../../../crates/suite-runtime" }
dirs = { workspace = true }
zip = { workspace = true }
installation_tools = { package = "devbox-installation-tools",path="../../../crates/installation-tools",default-features=false}
tauri-plugin-dialog = { workspace = true }
tauri-plugin-opener = { workspace = true }
devbox-catalog = { package = "catalog", path = "../../../crates/catalog" }
product-contract = { path = "../../../crates/product-contract" }
tauri = { workspace = true }
product-shell-tauri = { path = "../../../crates/product-shell-tauri" }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
reqwest = { workspace = true, features = ["default"] }
devbox-filesystem = { package = "filesystem", path = "../../../crates/filesystem" }

uuid = { workspace = true }
tokio = { workspace = true }


[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
