import type { WorkspaceIssue } from "../generated/WorkspaceIssue";
const unavailable = "작업을 완료하지 못했습니다. 상태를 확인하고 다시 시도해 주세요.";
/** Native static codes are exhaustive; unknown text never becomes user-visible diagnostics. */
export const workspaceMessages: Record<WorkspaceIssue, string> = {
  alias_limit: unavailable,
  binding_review_required: unavailable,
  busy: "앞선 작업이 끝난 뒤 다시 시도해 주세요.",
  commit_review_stale: "검토 이후 Git index 또는 HEAD가 바뀌었습니다. 다시 검토해 주세요.",
  component_args_invalid: unavailable,
  component_response_invalid: unavailable,
  context_busy: "파일 또는 Git 작업이 진행 중입니다. 완료나 취소를 확인한 뒤 다시 시도해 주세요.",
  context_cancelled: unavailable,
  context_expired: unavailable,
  context_selection_expired: "프로젝트 확인 시간이 초과되었습니다. 다시 선택해 주세요.",
  context_unavailable: unavailable,
  definition_owner_busy: unavailable,
  definition_owner_reference_required: "비밀 및 API 환경 참조는 해당 연결 화면에서 변경해 주세요.",
  definition_preview_stale: "프로젝트 정의 확인이 만료되었습니다. 다시 검토해 주세요.",
  dependency_busy: "다른 Dependency Lens 분석 또는 원격 조회가 진행 중입니다.",
  dependency_context_changed: "프로젝트 연결이 변경되었습니다. 다시 선택한 뒤 분석해 주세요.",
  dependency_operation_failed:
    "의존성 분석이나 조회를 완료하지 못했습니다. 파일과 저장된 캐시 상태를 확인하고 다시 검토해 주세요.",
  dependency_review_required: "전송 내용을 다시 검토해 주세요.",
  duplicate_alias: unavailable,
  duplicate_imported_profile: "같은 보관본의 프로필이 이미 있습니다. 가져오기 검토를 다시 시작해 주세요.",
  duplicate_imported_template: "같은 보관본의 템플릿이 이미 있습니다. 가져오기 검토를 다시 시작해 주세요.",
  duplicate_worktree: unavailable,
  file_busy: unavailable,
  file_changed: "디스크의 파일이 변경되었습니다. 다시 불러오거나 파일을 다시 선택해 주세요.",
  file_context_changed: "파일을 연 프로젝트가 변경되었습니다. 해당 프로젝트를 다시 선택해 주세요.",
  file_context_limit: "이전 프로젝트의 편집 탭을 닫은 뒤 새 WSL 프로젝트를 열어 주세요.",
  file_delete_conflict: "파일이 변경되어 삭제하지 않았습니다. 상태를 다시 확인해 주세요.",
  file_dialog_unavailable: unavailable,
  file_limit: "열린 파일을 일부 닫은 뒤 다시 시도해 주세요.",
  file_listing_unavailable: unavailable,
  file_owner_path:
    "제품이 관리하는 설정과 승인 파일은 일반 편집기로 변경할 수 없습니다. 해당 설정 화면을 사용해 주세요.",
  file_path_limit: "이 파일의 경로가 너무 깊습니다.",
  file_preview_unavailable: unavailable,
  file_read_failed: "파일을 읽지 못했습니다. 연결 상태와 파일 크기·인코딩을 확인해 주세요.",
  file_read_only: unavailable,
  file_reference_busy: unavailable,
  file_reference_invalid: unavailable,
  file_reference_limit: unavailable,
  file_reference_stale: unavailable,
  file_rename_conflict: "파일 상태나 새 이름을 확인한 뒤 다시 시도해 주세요.",
  file_rename_unconfirmed:
    "이름 변경이 중단되어 원본과 대상이 함께 남아 있을 수 있습니다. 두 경로를 확인한 뒤 다시 시도해 주세요.",
  file_save_conflict: "파일이 변경되었거나 저장할 수 없습니다. 현재 내용을 보존한 채 파일 상태를 확인해 주세요.",
  file_selection_expired: unavailable,
  file_selection_required: "파일 선택 버튼에서 열 파일을 선택해 주세요.",
  file_snapshot_changed: "파일 상태가 변경되었습니다. 다시 불러온 뒤 시도해 주세요.",
  file_target_unavailable: "이 파일의 실행 환경을 아직 연결하지 못했습니다.",
  file_unavailable: unavailable,
  files_busy: unavailable,
  files_initialize_failed: "편집기 저장소를 준비하지 못했습니다. 저장된 정보를 확인해 주세요.",
  files_recovery_changed: "복구 버퍼가 다른 작업에서 변경되었습니다. 현재 버퍼를 유지하고 다시 검토해 주세요.",
  files_response_invalid: unavailable,
  files_session_changed:
    "저장된 세션이 변경되어 자동 저장을 멈췄습니다. 현재 편집을 저장한 뒤 프로젝트를 다시 선택하거나 앱을 다시 시작해 주세요.",
  files_store_changed: "편집기 저장소가 변경되었습니다. 앱을 다시 시작해 주세요.",
  files_store_limit: unavailable,
  files_store_unavailable: unavailable,
  files_unavailable: unavailable,
  git_config_invalid: "Git 설정 파일의 형식을 확인할 수 없습니다.",
  git_config_limit: unavailable,
  git_environment_invalid:
    "Git에 전달할 HOME과 실행 환경을 확인할 수 없습니다. Git 환경을 확인한 뒤 다시 검토해 주세요.",
  git_home_unavailable: unavailable,
  git_installation_unavailable:
    "Git for Windows 실행 파일과 설치 폴더를 확인할 수 없습니다. 설치 후 다시 검토해 주세요.",
  git_source_limit: "Git 설정·hook의 파일 수나 크기가 확인 가능한 범위를 넘었습니다.",
  git_source_path_invalid: unavailable,
  git_source_path_unsupported: "Git 설정 또는 hook이 확인할 수 없는 경로를 참조합니다. 실제 로컬 경로를 확인해 주세요.",
  git_source_transport_denied: unavailable,
  git_source_unavailable: "Git 실행 파일·설정·hook을 읽지 못했습니다. 파일과 연결 상태를 확인해 주세요.",
  git_sources_changed: unavailable,
  initializing: "저장된 정보를 불러오고 있습니다.",
  invalid_component_store: unavailable,
  invalid_context: unavailable,
  invalid_definition_digest: unavailable,
  invalid_file_choices: "최근 파일 정보를 읽지 못했습니다. 저장된 정보를 확인해 주세요.",
  invalid_file_path: unavailable,
  invalid_files_store: "편집기 설정이나 복구 파일을 읽지 못했습니다. 기존 파일을 확인해 주세요.",
  invalid_imported_profile: "가져온 프로필 형식을 확인하지 못했습니다. 저장된 내용은 유지됩니다.",
  invalid_imported_profile_binding: "가져온 프로필의 프로젝트 연결을 확인하지 못했습니다. 기존 정보는 유지됩니다.",
  invalid_imported_template: "가져온 템플릿 형식을 확인하지 못했습니다. 저장된 내용은 유지됩니다.",
  invalid_imported_template_reference: "템플릿 출처를 확인하지 못했습니다. 기존 정보는 유지됩니다.",
  invalid_legacy_choices: "항목의 현재 상태에 맞는 처리 방법을 선택해 주세요.",
  invalid_legacy_snapshot: "보관 기록을 검증하지 못했습니다. 기존 파일은 유지됩니다.",
  invalid_manifest: "프로젝트 정의 JSON을 읽지 못했습니다. 기존 파일은 보존됩니다.",
  invalid_manifest_definition: "프로젝트 정의의 작업·도구·참조 경로를 확인해 주세요.",
  invalid_object_evidence: unavailable,
  invalid_overlay: "이 컴퓨터의 프로젝트 설정을 읽지 못했습니다. 기존 파일은 보존됩니다.",
  invalid_overview_store: "프로젝트 설정을 읽지 못했습니다. 기존 파일을 확인해 주세요.",
  invalid_project: unavailable,
  invalid_registry: "프로젝트 목록을 읽지 못했습니다. 기존 파일을 확인해 주세요.",
  invalid_registry_directory: unavailable,
  invalid_repository: unavailable,
  invalid_request: unavailable,
  invalid_response: unavailable,
  invalid_revision: unavailable,
  invalid_root: unavailable,
  invalid_store_component: unavailable,
  invalid_store_generation: unavailable,
  invalid_store_root: unavailable,
  invalid_target: unavailable,
  invalid_worktree: unavailable,
  legacy_file_limit: "기존 설정 파일이 보관 크기 제한을 초과했습니다. 원본은 유지됩니다.",
  legacy_import_busy: "기존 설정을 보관하는 작업이 진행 중입니다.",
  legacy_import_cancelled: "기존 설정 보관을 취소했습니다.",
  legacy_import_stale: "이전 보관 작업입니다. 진행 상태를 다시 확인해 주세요.",
  legacy_import_timeout: "기존 설정 확인 시간이 초과되었습니다. 원본은 유지됩니다.",
  legacy_lsp_conflict: "현재 LSP 설정을 확인하고 교체를 선택해 주세요.",
  legacy_lsp_documents_open: "열린 파일 탭과 복구 검토를 모두 닫은 뒤 LSP 설정을 가져와 주세요.",
  legacy_lsp_limit: "LSP 설정 보관 이력이 한도에 도달했습니다. 기존 내용을 보존했습니다.",
  legacy_lsp_review_limit: "진행 중인 LSP 설정 가져오기를 완료하거나 취소해 주세요.",
  legacy_lsp_review_stale: "LSP 설정 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  legacy_lsp_unavailable: "확인한 보관본에서 LSP 설정을 읽지 못했습니다.",
  legacy_path_unavailable: "기존 설정 폴더를 읽을 수 없습니다. 연결된 경로나 접근 권한을 확인해 주세요.",
  legacy_profile_binding_conflict:
    "이 프로필 또는 폴더가 다른 항목과 연결되어 있습니다. 기존 연결을 검토한 뒤 다시 시도해 주세요.",
  legacy_profile_distro_mismatch: "프로필에 보관된 이름과 일치하는 WSL 배포판을 선택하세요.",
  legacy_profile_review_limit: "진행 중인 프로필 가져오기 검토를 완료하거나 취소해 주세요.",
  legacy_profile_review_stale: "프로필 가져오기 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  legacy_profile_target_missing: "이 프로필에는 선택한 환경의 폴더가 없습니다.",
  legacy_profiles_unavailable: "검증을 마친 Workbench 프로젝트 프로필이 필요합니다. 보관 내용을 다시 확인해 주세요.",
  legacy_recovery_conflict: "같은 파일의 다른 버퍼를 바꾸려면 내용을 확인하고 교체를 선택해 주세요.",
  legacy_recovery_documents_open: "열린 파일 탭과 복구 검토를 모두 닫은 뒤 다시 시도해 주세요.",
  legacy_recovery_limit: "복구 버퍼 또는 보관 이력의 한도에 도달했습니다. 기존 내용을 보존했습니다.",
  legacy_recovery_no_files: "현재 프로젝트나 직접 선택한 파일에 해당하는 미저장 버퍼가 없습니다. 원본은 보관했습니다.",
  legacy_recovery_review_limit: "진행 중인 복구 버퍼 가져오기를 완료하거나 취소해 주세요.",
  legacy_recovery_review_stale: "복구 버퍼 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  legacy_recovery_unavailable: "확인한 보관본에서 미저장 버퍼를 읽지 못했습니다.",
  legacy_session_conflict: "현재 세션을 바꾸는 데 동의한 뒤 다시 검토해 주세요.",
  legacy_session_documents_open: "Files의 열린 탭을 모두 닫은 뒤 세션 가져오기를 검토해 주세요.",
  legacy_session_limit: "세션 또는 보관 기록 한도에 도달했습니다. 기존 내용은 유지됩니다.",
  legacy_session_no_files:
    "현재 프로젝트에서 복원할 파일이 없습니다. 해당 프로젝트를 선택하거나 대상 파일을 파일 선택 창으로 열고 탭을 닫은 뒤 다시 검토해 주세요.",
  legacy_session_review_limit: "진행 중인 세션 가져오기 검토를 완료하거나 취소해 주세요.",
  legacy_session_review_stale: "세션 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  legacy_session_unavailable: "Overview에서 Code Pad 보관본의 세션 파일을 먼저 확인해 주세요.",
  legacy_snapshot_changed: "보관 파일이 변경되어 덮어쓰지 않았습니다. 원본은 유지됩니다.",
  legacy_snapshot_incomplete: "완료되지 않은 보관 작업입니다. 같은 원본으로 다시 시도해 주세요.",
  legacy_snapshot_limit: "보관 작업이 32개 한도에 도달했습니다. 기존 보관 파일은 유지됩니다.",
  legacy_snapshot_unavailable: "설정을 보관할 수 없습니다. 저장 공간과 폴더 상태를 확인해 주세요.",
  legacy_source_changed: "확인하는 동안 기존 설정이 바뀌었습니다. 기존 앱을 닫고 다시 시도해 주세요.",
  legacy_template_review_limit: "진행 중인 템플릿 가져오기 검토를 완료하거나 취소해 주세요.",
  legacy_template_review_stale: "템플릿 가져오기 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  legacy_templates_unavailable: "검증을 마친 Workbench 프로젝트 템플릿이 필요합니다. 보관 내용을 다시 확인해 주세요.",
  legacy_window_unavailable: "검증을 마친 기존 창 상태가 필요합니다. 보관 내용을 다시 확인해 주세요.",
  legacy_workspace_limit: "보관한 작업 폴더 경로가 길이 제한을 초과했습니다. 원본은 유지됩니다.",
  legacy_workspace_unsupported: "이 작업 폴더는 Windows 폴더 등록을 지원하지 않습니다. 보관한 경로는 유지됩니다.",
  logs_owner_unavailable: "로그 보기 설정을 열지 못했습니다. 기존 설정은 보존되어 있습니다.",
  lsp_already_running: "언어 서버가 이미 실행 중입니다.",
  lsp_approval_changed: "LSP 실행 승인이 변경되었습니다. 다시 검토해 주세요.",
  lsp_approval_future: "현재 버전에서 읽을 수 없는 LSP 실행 승인을 보존했습니다.",
  lsp_approval_invalid: "저장된 LSP 실행 승인을 확인하지 못했습니다.",
  lsp_archive_changed: "선택한 archive가 변경되었습니다. 파일을 다시 선택해 주세요.",
  lsp_archive_limit: "archive 선택은 32개·합계 512 MiB까지 가능합니다.",
  lsp_archive_selection_invalid: "archive 선택이 만료되었습니다. 파일을 다시 선택해 주세요.",
  lsp_archive_unavailable: unavailable,
  lsp_archive_unsafe: "연결된 경로 대신 실제 archive 파일을 선택해 주세요.",
  lsp_busy: "다른 LSP 작업이 진행 중입니다. 잠시 후 다시 시도해 주세요.",
  lsp_command_unavailable: "선택한 언어 서버와 runtime 경로를 확인해 주세요.",
  lsp_config_changed: "LSP 설정이 변경되었습니다. 설정 화면을 다시 열어 확인해 주세요.",
  lsp_config_future: "현재 버전에서 읽을 수 없는 LSP 설정을 보존했습니다.",
  lsp_config_invalid: "LSP 설정을 확인해 주세요.",
  lsp_config_recovery_required: "손상된 LSP 설정은 명시적으로 복구해야 저장할 수 있습니다.",
  lsp_context_changed: "LSP 프로젝트 또는 실행 근거가 변경되었습니다. 다시 검토해 주세요.",
  lsp_disabled: "LSP가 비활성화되어 있습니다.",
  lsp_document_denied: unavailable,
  lsp_environment_unavailable: "언어 서버의 PATH와 HOME 환경을 확인하지 못했습니다.",
  lsp_executable_format_unsupported:
    "실행 대상에 맞는 네이티브 실행 파일을 선택해 주세요. WSL에서는 Linux ELF 실행 파일과 명시적인 Node 진입 파일을 사용합니다.",
  lsp_execution_approval_required: "현재 프로젝트의 언어 서버 실행 설정을 검토하고 승인해 주세요.",
  lsp_feature_unsupported: "언어 서버가 이 기능을 지원하지 않습니다.",
  lsp_index_corrupt: "관리형 서버 설치 목록 복구가 필요합니다",
  lsp_install_busy: "다른 LSP 설치 작업이 진행 중입니다.",
  lsp_install_failed: "관리형 서버 설치를 완료하지 못했습니다. 파일 검증과 연결 상태를 확인해 주세요.",
  lsp_install_io_unavailable: "관리형 서버의 설치·보관 파일을 읽거나 쓸 수 없습니다. 폴더 상태를 확인해 주세요.",
  lsp_install_path_unsafe: "관리형 서버의 설치·보관 폴더에 연결된 경로나 지원하지 않는 파일이 있습니다.",
  lsp_install_status_invalid: "관리형 서버 상태 응답을 확인하지 못했습니다.",
  lsp_installation_unavailable: "관리형 언어 서버 설치 상태를 확인해 주세요.",
  lsp_not_running: "언어 서버가 실행 중이 아닙니다.",
  lsp_operation_cancelled: "LSP 작업이 취소되었습니다.",
  lsp_recovery_conflict:
    "대상 파일 탭을 닫고 다시 검토해 주세요. 파일·백업·접근 권한이 변경된 경우 복원을 거부하고 원본을 보존합니다.",
  lsp_recovery_limit: "진행 중인 복구 검토를 먼저 완료하거나 취소해 주세요.",
  lsp_recovery_stale: "복구 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  lsp_recovery_unavailable: "이름 변경 복구 기록을 확인하지 못했습니다. 원본은 보존했습니다.",
  lsp_response_limit: unavailable,
  lsp_review_busy: "진행 중인 LSP 실행 검토를 먼저 완료하거나 취소해 주세요.",
  lsp_review_expired: "LSP 실행 검토가 만료되었습니다. 다시 검토해 주세요.",
  lsp_settings_changed: "저장된 언어 서버 설정이 검토 후 변경되었습니다. 다시 검토해 주세요.",
  lsp_settings_save_required: "언어 서버 사용을 선택하고 설정을 저장한 뒤 실행을 검토해 주세요.",
  lsp_shutdown_unconfirmed: "언어 서버 종료를 아직 확인하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  lsp_source_limit: "LSP 실행 검토 범위가 허용된 크기를 초과했습니다.",
  lsp_source_path_invalid: "LSP 실행 경로에 연결된 경로나 지원하지 않는 파일이 있습니다.",
  lsp_source_transport_denied: "선택한 프로젝트와 연결된 로컬 실행 경로를 사용해 주세요.",
  lsp_source_unavailable: "LSP 실행 파일을 읽지 못했습니다. 경로와 접근 권한을 확인해 주세요.",
  lsp_sources_changed: "LSP 실행 파일이 변경되었습니다. 다시 검토해 주세요.",
  lsp_start_in_progress: "언어 서버 시작이 이미 진행 중입니다.",
  lsp_target_unavailable: "이 실행 대상의 LSP 연결을 아직 사용할 수 없습니다.",
  lsp_unavailable: "언어 서버 작업을 완료하지 못했습니다. 실행 상태와 검토한 설정을 확인해 주세요.",
  manifest_limit: unavailable,
  migration_busy: unavailable,
  migration_unavailable: unavailable,
  native_path_transport_denied:
    "이 드라이브 연결을 확인할 수 없습니다. 실제 로컬 경로나 직접 선택한 Windows 공유 경로를 사용해 주세요.",
  native_worker_unavailable: unavailable,
  problem_context_invalid: unavailable,
  problem_context_required: unavailable,
  problem_invalid: unavailable,
  problem_log_expired: unavailable,
  problem_revision_invalid: unavailable,
  problem_source_expired: unavailable,
  problem_source_invalid: unavailable,
  problem_source_limit: unavailable,
  problem_source_superseded: unavailable,
  problem_source_unavailable: unavailable,
  problem_stale: unavailable,
  problem_target_invalid: unavailable,
  problem_target_missing: unavailable,
  problems_busy: unavailable,
  problems_unavailable: unavailable,
  process_action_stale: "선택한 프로세스 또는 실행이 바뀌었습니다. 새로 고친 뒤 다시 선택해 주세요.",
  process_observation_unavailable: "프로세스와 포트 정보를 읽지 못했습니다. 이전 목록은 유지됩니다.",
  process_owner_unavailable: "Runtime 보기 설정을 열지 못했습니다. 기존 설정은 보존되어 있습니다.",
  process_owner_unsettled:
    "실행 중인 작업의 프로세스 소유권을 확인 중입니다. 작업 상태가 확인된 뒤 다시 시도해 주세요.",
  project_binding_changed: "등록한 폴더가 교체되었습니다. 폴더를 확인하고 경로를 다시 연결해 주세요.",
  project_definition_changed: "프로젝트 정의나 참조 파일이 변경되었습니다. 다시 확인해 주세요.",
  project_definition_limit: "프로젝트 정의의 파일 수나 크기가 허용 범위를 넘었습니다.",
  project_definition_unavailable: "프로젝트 정의의 참조 파일을 읽지 못했습니다. 경로와 연결 상태를 확인해 주세요.",
  project_has_legacy_references: "이 프로젝트를 참조하는 항목이 있어 등록을 해제할 수 없습니다.",
  project_object_changed: "확인한 폴더가 변경되었습니다. 다시 확인해 주세요.",
  project_object_unavailable: "폴더 또는 Git 정보를 읽지 못했습니다.",
  project_preview_limit: unavailable,
  project_preview_stale: "등록 확인이 만료되었습니다. 폴더를 다시 확인해 주세요.",
  project_probe_timeout: "폴더 확인 시간이 초과되었습니다. 연결 상태를 확인해 주세요.",
  project_provider_busy: unavailable,
  project_provider_invalid: unavailable,
  project_provider_limit: unavailable,
  project_provider_stale: unavailable,
  project_selection_required: "개요에서 작업할 프로젝트를 선택해 주세요.",
  query_cancelled: unavailable,
  recovery_preview_stale: "복구 대상이 변경되었습니다. 미리보기를 다시 확인해 주세요.",
  recovery_unavailable: "저장된 복구 내용을 확인하지 못했습니다.",
  referenced_worktree: unavailable,
  registry_changed_after_save: unavailable,
  registry_changed_during_read: unavailable,
  registry_changed_during_review: unavailable,
  registry_invalid: unavailable,
  registry_limit: unavailable,
  registry_owner_busy: unavailable,
  registry_owner_changed: unavailable,
  registry_owner_unavailable: unavailable,
  registry_read_failed: unavailable,
  registry_retired_import_data:
    "v0.7에서 가져온 프로젝트 정보가 남아 있어 열 수 없습니다. v0.8.1에서 프로젝트를 다시 등록한 뒤 업데이트해 주세요.",
  registry_save_failed: unavailable,
  registry_store_busy: unavailable,
  rejected: unavailable,
  repository_identity_conflict: unavailable,
  repository_reassignment_required: unavailable,
  request_cancelled: "작업이 취소되었습니다.",
  request_expired: "작업 대기 시간이 초과되었습니다. 다시 시도해 주세요.",
  revision_limit: unavailable,
  "runtime-helper-unavailable": unavailable,
  "runtime-target-changed": unavailable,
  "runtime-target-invalid": unavailable,
  runtime_container_engine_unsupported: unavailable,
  runtime_container_owner_unavailable: unavailable,
  runtime_context_required: unavailable,
  runtime_control_failed: "실행 요청이 실패했습니다. 이력과 실행 상태를 확인한 뒤 새로 시도할 수 있습니다.",
  runtime_control_in_progress: "같은 실행 요청이 처리 중입니다. 작업 상태를 확인한 뒤 다시 시도해 주세요.",
  runtime_control_owner_unsettled: "이전 실행의 종료가 아직 확인되지 않았습니다. 작업 상태를 확인해 주세요.",
  runtime_control_recovery_required:
    "중단된 요청을 자동으로 다시 실행하지 않았습니다. 실행 요청 복구에서 현재 상태를 확인해 주세요.",
  runtime_control_unavailable: "실행 요청을 저장하거나 확인하지 못했습니다. 같은 요청으로 다시 시도해 주세요.",
  runtime_diagnostic_target_mismatch: "진단 파일과 같은 프로젝트를 선택한 뒤 다시 열어 주세요.",
  runtime_handoff_review_required: unavailable,
  runtime_import_busy: "다른 가져오기 작업이 진행 중입니다.",
  runtime_import_destination_conflict: "현재 데이터와 충돌합니다. 기존 내용을 보존했습니다.",
  runtime_import_stale: "보존된 사본을 다시 검토해 주세요.",
  runtime_log_changed: "로그 소유권이 바뀌었습니다. 해당 실행에서 로그를 다시 열어 주세요.",
  runtime_log_unavailable: "이 실행의 로그가 삭제되었거나 읽을 수 없습니다.",
  runtime_navigation_unavailable: "선택한 작업이나 로그 화면으로 이동하지 못했습니다.",
  runtime_operation_unavailable: "실행 작업을 완료하지 못했습니다. 작업 상태와 설정을 확인해 주세요.",
  runtime_owner_unavailable: "실행 저장소를 열지 못했습니다. 기존 데이터는 보존되어 있습니다.",
  runtime_settings_busy: "다른 보기 설정 작업이 진행 중입니다.",
  runtime_settings_conflict: "검토 후 설정이 바뀌었거나 교체 선택이 필요합니다. 다시 검토해 주세요.",
  runtime_settings_invalid: "기존 보기 설정의 형식이나 source를 확인해 주세요.",
  runtime_settings_stale: "설정 검토가 만료되었습니다. 보존한 사본을 다시 검토해 주세요.",
  runtime_settings_unavailable: "보기 설정을 읽거나 저장하지 못했습니다. 기존 사본은 보존되어 있습니다.",
  runtime_store_changed: "실행 저장소가 변경되었습니다. 앱을 다시 시작해 주세요.",
  runtime_task_review_required: "작업 실행 내용을 검토하고 승인해 주세요.",
  runtime_task_source_changed: "작업 정의가 변경되었습니다. 가져오기와 실행 승인을 다시 확인해 주세요.",
  runtime_windows_required: unavailable,
  selection_busy: unavailable,
  selection_expired: unavailable,
  selection_invalid: unavailable,
  selection_limit: unavailable,
  selection_stale: unavailable,
  session_archive_limit: unavailable,
  session_archive_unavailable: unavailable,
  session_archived: unavailable,
  session_args_invalid: unavailable,
  session_changed: unavailable,
  session_cleanup_pending: unavailable,
  session_context_changed: unavailable,
  session_context_required: unavailable,
  session_identity_conflict: unavailable,
  session_limit: unavailable,
  session_method_denied: unavailable,
  session_missing: unavailable,
  session_native_owner_lost: unavailable,
  session_not_approved: unavailable,
  session_operation_conflict: unavailable,
  session_operation_invalid: unavailable,
  session_operation_missing: unavailable,
  session_owner_busy: unavailable,
  session_owner_unavailable: unavailable,
  session_phase_changed: unavailable,
  session_phase_expired: unavailable,
  session_plan_changed: unavailable,
  session_plan_invalid: unavailable,
  session_preflight_blocked: unavailable,
  session_preflight_busy: unavailable,
  session_readiness_expired: unavailable,
  session_readiness_failed: unavailable,
  session_resource_changed: unavailable,
  session_resource_conflict: unavailable,
  session_resource_exists: unavailable,
  session_resource_invalid: unavailable,
  session_resource_limit: unavailable,
  session_resource_missing: unavailable,
  session_resource_start_failed: unavailable,
  session_resource_stop_failed: unavailable,
  session_runtime_unavailable: unavailable,
  session_start_pending: unavailable,
  session_store_changed: unavailable,
  session_store_invalid: unavailable,
  session_summary_invalid: unavailable,
  session_summary_missing: unavailable,
  session_summary_stale: unavailable,
  session_summary_unavailable: unavailable,
  session_task_conflict: "세션이 참조하는 작업을 먼저 조정해 주세요.",
  setup_required: unavailable,
  source_cancelled: "Git 작업을 취소했습니다.",
  source_cleanup_open_files: "해당 작업 폴더에 열린 파일 탭이 있습니다. 탭을 닫은 뒤 정리 후보를 다시 검사해 주세요.",
  source_cleanup_scope_changed:
    "정리 범위의 프로젝트나 Git 실행 근거가 바뀌었습니다. 범위를 다시 검토하거나 철회해 주세요.",
  source_cleanup_scope_invalid: "저장된 정리 범위를 확인하지 못했습니다. 기존 파일을 보존했습니다.",
  source_context_changed: "프로젝트 또는 Git 실행 근거가 변경되었습니다. 승인 상태를 다시 확인해 주세요.",
  source_operation_unavailable: "Git 작업을 완료하지 못했습니다. 저장소 상태와 실행 승인을 확인해 주세요.",
  source_owner_unavailable: unavailable,
  source_preview_stale: "Git 실행 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  source_requires_repository: "이 프로젝트 폴더에는 Git 저장소가 없습니다.",
  source_review_required: "Git 설정이나 실행 근거를 다시 검토해 주세요.",
  source_trust_changed: unavailable,
  source_trust_future: unavailable,
  source_trust_invalid: "저장된 Git 승인을 확인할 수 없습니다. 기존 파일을 보존했습니다.",
  stale_context: "프로젝트 연결이 변경되었습니다. 작업 폴더를 다시 선택해 주세요.",
  stale_overlay_binding: "이 컴퓨터의 설정이 이전 프로젝트 연결을 사용합니다. 다시 검토해 주세요.",
  stale_registry: "프로젝트 목록이 변경되었습니다. 새로 고친 뒤 다시 시도해 주세요.",
  store_activation_failed: unavailable,
  store_already_active: unavailable,
  store_generation_changed: unavailable,
  store_generation_limit: unavailable,
  store_generation_unavailable: unavailable,
  store_owner_busy: "다른 작업에서 저장소를 사용하고 있습니다.",
  store_owner_changed: unavailable,
  store_owner_unavailable: unavailable,
  store_pointer_changed: "저장소가 변경되었습니다. 앱을 다시 시작해 주세요.",
  store_pointer_unavailable: unavailable,
  store_prepare_failed: unavailable,
  store_unavailable: unavailable,
  template_identity_changed: "템플릿 식별자가 바뀌었습니다. 편집을 다시 시작해 주세요.",
  template_name_conflict: "같은 이름의 활성 템플릿이 있습니다. 다른 이름을 사용해 주세요.",
  terminal_args_invalid: unavailable,
  terminal_command_conflict: unavailable,
  terminal_command_expired: unavailable,
  terminal_command_limit: unavailable,
  terminal_command_superseded: unavailable,
  terminal_context_changed: unavailable,
  terminal_distro_mismatch: unavailable,
  terminal_import_backup_invalid: unavailable,
  terminal_layout_changed: unavailable,
  terminal_layout_invalid: unavailable,
  terminal_layout_required: unavailable,
  terminal_log_context_changed: unavailable,
  terminal_log_delivery_pending: unavailable,
  terminal_log_pending: unavailable,
  terminal_log_source_invalid: unavailable,
  terminal_main_unavailable: unavailable,
  terminal_method_invalid: unavailable,
  terminal_operation_conflict: unavailable,
  terminal_operation_failed: unavailable,
  terminal_operation_invalid: unavailable,
  terminal_owner_busy: unavailable,
  terminal_owner_changed: unavailable,
  terminal_owner_unavailable: unavailable,
  terminal_pane_conflict: unavailable,
  terminal_peer_denied: unavailable,
  terminal_preferences_changed: unavailable,
  terminal_preferences_invalid: unavailable,
  terminal_profile_changed: unavailable,
  terminal_profile_invalid: unavailable,
  terminal_profile_missing: unavailable,
  terminal_profiles_changed: unavailable,
  terminal_profiles_invalid: unavailable,
  terminal_request_denied: unavailable,
  terminal_restore_conflict: unavailable,
  terminal_restore_expired: unavailable,
  terminal_restore_failed: unavailable,
  terminal_restore_invalid: unavailable,
  terminal_retirement_pending: unavailable,
  terminal_session_limit: unavailable,
  terminal_session_missing: unavailable,
  terminal_session_stopping: unavailable,
  terminal_shell_integration_failed: unavailable,
  terminal_start_interrupted: unavailable,
  terminal_start_pending: unavailable,
  terminal_store_changed: unavailable,
  terminal_store_invalid: unavailable,
  terminal_target_invalid: unavailable,
  terminal_window_invalid: unavailable,
  terminal_window_unavailable: unavailable,
  terminal_windows_required: unavailable,
  terminal_worker_unavailable: unavailable,
  unavailable: unavailable,
  unknown_component: unavailable,
  unknown_imported_profile: "가져온 프로필을 찾지 못했습니다. 프로젝트 목록을 새로 고쳐 주세요.",
  unknown_imported_template: "가져온 템플릿을 찾지 못했습니다. 프로젝트 목록을 새로 고쳐 주세요.",
  unknown_project: unavailable,
  unsafe_file_path: "연결된 경로 대신 실제 파일을 선택해 주세요.",
  unsafe_project_definition: "프로젝트 밖이나 연결된 경로의 정의는 사용할 수 없습니다.",
  unsafe_project_object: "연결된 경로는 등록할 수 없습니다. 실제 폴더를 선택해 주세요.",
  unsupported_manifest_version: "지원하지 않는 프로젝트 정의 버전입니다. 기존 파일은 보존됩니다.",
  unsupported_overlay_version: "지원하지 않는 로컬 설정 버전입니다. 기존 파일은 보존됩니다.",
  unsupported_registry_version: unavailable,
  unsupported_store_version: unavailable,
  webhook_log_busy: unavailable,
  webhook_log_expired: unavailable,
  webhook_log_invalid: unavailable,
  webhook_log_limit: unavailable,
  webhook_log_stale: unavailable,
  window_apply_failed: "창 상태 변경을 완료하지 못했습니다. 보관한 이전 창 상태에서 복원을 검토할 수 있습니다.",
  window_history_limit: "창 상태 기록이 32개 한도에 도달했습니다. 기존 기록을 유지합니다.",
  window_history_unavailable: "이전 창 상태 기록을 읽지 못했습니다. 보관된 파일은 유지됩니다.",
  window_monitor_unavailable: "현재 모니터와 배율을 확인하지 못했습니다. 화면 연결 상태를 확인해 주세요.",
  window_replace_required: "현재 창 위치와 크기 변경에 동의한 뒤 다시 검토해 주세요.",
  window_review_limit: "진행 중인 창 상태 검토를 완료하거나 취소해 주세요.",
  window_review_stale: "창 위치나 화면 구성이 바뀌었거나 검토가 만료되었습니다. 다시 검토해 주세요.",
  window_state_invalid: "창 위치와 크기의 저장 형식을 확인하지 못했습니다. 원본을 유지합니다.",
  window_state_unavailable: "현재 창 상태를 확인하지 못했습니다. 기본 창을 표시한 뒤 다시 검토해 주세요.",
  window_unavailable: unavailable,
  windows_required: unavailable,
  worker_unavailable: unavailable,
  workspace_command_invalid: unavailable,
  workspace_command_unavailable: unavailable,
  workspace_context_required: unavailable,
  workspace_context_stale: unavailable,
  workspace_query_mode_unavailable: unavailable,
  workspace_runtime_invalid: unavailable,
  workspace_runtime_stale: unavailable,
  workspace_runtime_unavailable: unavailable,
  workspace_shortcut_unavailable: unavailable,
  workspace_source_busy: unavailable,
  workspace_source_unavailable: unavailable,
  workspace_summary_invalid: unavailable,
  workspace_summary_stale: unavailable,
  workspace_terminal_invalid: unavailable,
  workspace_window_unavailable: unavailable,
  worktree_branch_invalid: "새 branch 이름을 확인해 주세요.",
  worktree_preview_stale: "작업 폴더 생성 확인이 만료되었거나 실행 근거가 바뀌었습니다. 다시 검토해 주세요.",
  worktree_target_changed: "확인한 부모 폴더가 바뀌었거나 대상 폴더가 생겼습니다. 다시 검토해 주세요.",
  worktree_target_invalid:
    "기존 부모 폴더 아래의 새 작업 폴더 경로를 선택해 주세요. Git 메타데이터 안에는 만들 수 없습니다.",
  worktree_target_unavailable: "생성할 위치의 부모 폴더를 읽지 못했습니다. 경로와 연결 상태를 확인해 주세요.",
  wsl_admission_required: "WSL 프로젝트 연결은 아직 사용할 수 없습니다.",
  wsl_backing_object_changed: "WSL 가상 디스크가 교체되었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_backing_path_unsafe: "WSL 가상 디스크 경로가 바뀌었습니다. 배포판 저장 위치를 확인해 주세요.",
  wsl_backing_unavailable: "WSL 가상 디스크의 식별 정보를 읽지 못했습니다.",
  wsl_connection_busy: unavailable,
  wsl_connection_closed: "WSL 연결이 종료되었습니다. 배포판 상태를 확인하고 다시 연결해 주세요.",
  wsl_container_action_failed: unavailable,
  wsl_context_invalid: "WSL 프로젝트 문맥을 확인하지 못했습니다. 프로젝트를 다시 선택해 주세요.",
  wsl_context_required: "WSL 파일을 열기 전에 프로젝트 연결을 확인해 주세요.",
  wsl_control_changed: unavailable,
  wsl_control_conflict: unavailable,
  wsl_control_invalid: unavailable,
  wsl_control_limit: unavailable,
  wsl_control_review_required: unavailable,
  wsl_controls_invalid: unavailable,
  wsl_distro_invalid: unavailable,
  wsl_distro_missing: "WSL 배포판 등록을 찾을 수 없습니다. 목록을 새로 고쳐 주세요.",
  wsl_distro_stopped: "WSL 배포판이 중지되어 있습니다. 목록을 새로 고친 뒤 시작 여부를 선택해 주세요.",
  wsl_document_proof_invalid: unavailable,
  wsl_executable_changed: unavailable,
  wsl_executable_unavailable: unavailable,
  wsl_execution_conflict: unavailable,
  wsl_filesystem_unavailable: "WSL 파일시스템 정보를 읽지 못했습니다. 배포판 상태를 확인해 주세요.",
  wsl_helper_changed: "WSL 연결 파일이 변경되었습니다. Workspace를 다시 설치한 뒤 확인해 주세요.",
  wsl_helper_unavailable: "WSL 연결 파일을 확인하지 못했습니다. Workspace 설치 상태를 확인해 주세요.",
  wsl_identity_unavailable: "이 WSL 파일시스템의 폴더 식별 정보를 확인할 수 없습니다.",
  wsl_lsp_installed_target_required: "WSL 배포판에 설치된 언어 서버 또는 Node 진입 파일을 직접 지정해 주세요.",
  wsl_lsp_language_unsupported: "이 WSL 언어 서버의 언어는 아직 지원하지 않습니다.",
  wsl_native_filesystem_required:
    "배포판의 기본 Linux 파일시스템 폴더를 선택해 주세요. 다른 마운트의 파일은 아직 지원하지 않습니다.",
  wsl_operation_failed: "WSL 폴더를 확인하지 못했습니다. 경로와 접근 권한을 확인해 주세요.",
  wsl_output_invalid: unavailable,
  wsl_output_limit: unavailable,
  wsl_protocol_invalid: unavailable,
  wsl_registration_changed: "WSL 배포판 등록이 교체되었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_registry_changed: "WSL 배포판이나 디스크가 바뀌었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_registry_entry_missing: "조회 중 WSL 등록 항목이 사라졌습니다. 배포판 목록을 새로 고쳐 주세요.",
  wsl_registry_invalid: unavailable,
  wsl_registry_limit: unavailable,
  wsl_registry_list_changed: "WSL 배포판 목록이 갱신 중입니다. 잠시 후 다시 확인해 주세요.",
  wsl_registry_read_changed: "WSL 등록 정보가 갱신 중입니다. 잠시 후 폴더 연결을 다시 검토해 주세요.",
  wsl_registry_unavailable: unavailable,
  wsl_request_cancelled: "WSL 파일 작업이 취소되었습니다. 편집 내용은 유지됩니다.",
  wsl_request_invalid: unavailable,
  wsl_retained_registration_changed: "WSL 배포판의 등록 값이 바뀌었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_reveal_path_unavailable: "이 WSL 파일 이름은 Windows 탐색기에서 표시할 수 없습니다.",
  wsl_root_changed: "WSL 폴더나 저장소가 바뀌었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_root_expired: "WSL 폴더 검토가 만료되었습니다. 폴더를 다시 확인해 주세요.",
  wsl_shutdown_unconfirmed: "WSL 파일 연결의 종료를 확인하지 못했습니다. 편집 내용을 보존하고 다시 시도해 주세요.",
  wsl_snapshot_unavailable: unavailable,
  wsl_source_method_unavailable: "이 WSL Git 작업은 아직 사용할 수 없습니다.",
  wsl_source_required: unavailable,
  wsl_storage_object_changed: "WSL 배포판 저장 폴더가 교체되었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_storage_path_unsafe:
    "WSL 저장 폴더 경로에 링크나 접근할 수 없는 폴더가 있습니다. 배포판 저장 위치를 확인해 주세요.",
  wsl_storage_unavailable: "WSL 배포판 저장 폴더의 식별 정보를 읽지 못했습니다. 경로와 접근 권한을 확인해 주세요.",
  wsl_target_retirement_pending: unavailable,
  wsl_target_unavailable: unavailable,
  wsl_timeout: "WSL 연결 시간이 초과되었습니다. 배포판 상태를 확인해 주세요.",
  wsl_unavailable: unavailable,
};
export function knownIssueMessage(issue: string): string | undefined {
  return Object.prototype.hasOwnProperty.call(workspaceMessages, issue)
    ? workspaceMessages[issue as WorkspaceIssue]
    : undefined;
}
export function workspaceIssueMessage(issue: string): string {
  return knownIssueMessage(issue) ?? unavailable;
}
