import type { SearchIssue } from "../generated/SearchIssue";
export const searchMessages: Record<SearchIssue, string> = {
  component_args_invalid: "요청을 확인해 주세요.",
  component_state_conflict: "저장소 초기화를 완료하지 못했습니다. 앱을 다시 시작해 주세요.",
  file_reference_invalid: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_command_invalid: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_command_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_file_stale: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_query_mode_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_reference_invalid: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_reference_stale: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_source_busy: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_source_denied: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_source_invalid: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_source_stale: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  knowledge_source_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  migration_busy: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  migration_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  provider_unavailable: "연결할 수 없습니다. 현재 내용은 유지됩니다.",
  query_cancelled: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  search_busy: "다른 작업을 마친 뒤 다시 시도해 주세요.",
  search_limit: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  search_source_denied: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  search_stale: "검색 결과가 오래되었거나 파일 연결이 바뀌었습니다. 다시 검색해 주세요.",
  search_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  setup_required: "저장소를 먼저 준비해 주세요.",
  component_response_invalid: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  component_state_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  component_storage_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  component_store_exists: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  import_row_invalid: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  root_unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  unavailable: "검색 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
};
