import mermaid from "mermaid";
import { useEffect, useRef } from "react";
import { applySvgResult } from "../lib/previewState";
import type { PreviewResponse } from "../types";

// Mermaid receives only the standalone source returned by the native command.
// Keep strict mode: lowering it would allow diagram text to create active DOM.
mermaid.initialize({ startOnLoad: false, theme: "dark", securityLevel: "strict" });

interface PreviewPaneProps {
  docPath: string;
  response: PreviewResponse | null;
  error: string | null;
}

/**
 * Preview HTML is already sanitized by crates/markdown.  Mermaid SVG is
 * generated by Mermaid's strict renderer; failed renders retain the last
 * successful SVG for that block and show a small error badge.
 */
export default function PreviewPane({ docPath, response, error }: PreviewPaneProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const lastGoodSvg = useRef<Map<string, string>>(new Map());
  const renderSequence = useRef(0);

  useEffect(() => {
    lastGoodSvg.current.clear();
  }, [docPath]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container || !response) return;
    let cancelled = false;
    const renderBlocks = async () => {
      if (response.kind === "mermaid") {
        const source = response.source;
        const key = "standalone";
        try {
          const { svg } = await mermaid.render(
            `code-pad-mermaid-${renderSequence.current++}`,
            source,
          );
          const applied = applySvgResult(lastGoodSvg.current, key, { ok: true, svg });
          if (!cancelled && containerRef.current === container) container.innerHTML = applied.svg;
        } catch {
          const applied = applySvgResult(lastGoodSvg.current, key, { ok: false });
          if (!cancelled) {
            container.innerHTML = `${applied.svg}<span class="mermaid-error-badge" title="mermaid 구문 오류">⚠ 구문 오류</span>`;
          }
        }
        return;
      }

      const blocks = container.querySelectorAll<HTMLDivElement>(".mermaid-block[data-idx]");
      await Promise.all(
        Array.from(blocks).map(async (element) => {
          const index = Number(element.dataset.idx);
          const source = response.mermaid[index];
          if (source === undefined) return;
          const key = String(index);
          try {
            const { svg } = await mermaid.render(
              `code-pad-mermaid-${index}-${renderSequence.current++}`,
              source,
            );
            const applied = applySvgResult(lastGoodSvg.current, key, { ok: true, svg });
            if (!cancelled) element.innerHTML = applied.svg;
          } catch {
            const applied = applySvgResult(lastGoodSvg.current, key, { ok: false });
            if (!cancelled) {
              element.innerHTML = `${applied.svg}<span class="mermaid-error-badge" title="mermaid 구문 오류">⚠ 구문 오류</span>`;
            }
          }
        }),
      );
    };

    if (response.kind === "markdown") {
      // The native markdown crate has already sanitized this HTML.  It is the
      // only value in the app that is intentionally assigned as HTML.
      container.innerHTML = response.html;
    } else {
      container.replaceChildren();
    }
    void renderBlocks();
    return () => {
      cancelled = true;
    };
  }, [docPath, response]);

  return (
    <aside className="preview-pane" aria-label="프리뷰">
      <div className="preview-pane-header">
        <span>프리뷰</span>
        <span className="preview-pane-path">{docPath}</span>
      </div>
      {error && (
        <p className="preview-error" role="alert">
          {error}
        </p>
      )}
      {!response ? (
        <p className="preview-empty">렌더링 중...</p>
      ) : (
        <div ref={containerRef} className="preview-body" />
      )}
    </aside>
  );
}
