import { invoke } from "@tauri-apps/api/core";
import { describe, makeRequest, type Description } from "@devbox/product-shell/api";
import { isOperation, problemMessage } from "@devbox/product-shell/operation";
import { WorkspaceOperationError } from "@devbox/workspace-features/transport";
import catalog from "../../products.json";

const issues: Record<string, string> = {
  source_cleanup_scope_invalid: "저장된 정리 범위를 확인하지 못했습니다. 기존 파일을 보존했습니다.",
  source_cleanup_scope_changed: "정리 범위의 프로젝트나 Git 실행 근거가 바뀌었습니다. 범위를 다시 검토하거나 철회해 주세요.",
  source_cleanup_open_files: "해당 작업 폴더에 열린 파일 탭이 있습니다. 탭을 닫은 뒤 정리 후보를 다시 검사해 주세요.",
  source_review_required: "Git 설정이나 실행 근거를 다시 검토해 주세요.",
  source_cancelled: "Git 작업을 취소했습니다.",
  worktree_branch_invalid: "새 branch 이름을 확인해 주세요.",
  worktree_preview_stale: "작업 폴더 생성 확인이 만료되었거나 실행 근거가 바뀌었습니다. 다시 검토해 주세요.",
  worktree_target_invalid: "기존 부모 폴더 아래의 새 작업 폴더 경로를 선택해 주세요. Git 메타데이터 안에는 만들 수 없습니다.",
  worktree_target_changed: "확인한 부모 폴더가 바뀌었거나 대상 폴더가 생겼습니다. 다시 검토해 주세요.",
  worktree_target_unavailable: "생성할 위치의 부모 폴더를 읽지 못했습니다. 경로와 연결 상태를 확인해 주세요.",
  source_requires_repository: "이 프로젝트 폴더에는 Git 저장소가 없습니다.",
  source_context_changed: "프로젝트 또는 Git 실행 근거가 변경되었습니다. 승인 상태를 다시 확인해 주세요.",
  source_preview_stale: "Git 실행 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  source_trust_invalid: "저장된 Git 승인을 확인할 수 없습니다. 기존 파일을 보존했습니다.",
  source_operation_unavailable: "Git 작업을 완료하지 못했습니다. 저장소 상태와 실행 승인을 확인해 주세요.",
  git_source_limit: "Git 설정·hook의 파일 수나 크기가 확인 가능한 범위를 넘었습니다.",
  git_config_invalid: "Git 설정 파일의 형식을 확인할 수 없습니다.",
  git_environment_invalid: "Git에 전달할 HOME과 실행 환경을 확인할 수 없습니다. Git 환경을 확인한 뒤 다시 검토해 주세요.",
  git_source_unavailable: "Git 실행 파일·설정·hook을 읽지 못했습니다. 파일과 연결 상태를 확인해 주세요.",
  git_installation_unavailable: "Git for Windows 실행 파일과 설치 폴더를 확인할 수 없습니다. 설치 후 다시 검토해 주세요.",
  git_source_path_unsupported: "Git 설정 또는 hook이 확인할 수 없는 경로를 참조합니다. 실제 로컬 경로를 확인해 주세요.",
  dependency_busy: "다른 Dependency Lens 분석 또는 원격 조회가 진행 중입니다.",
  dependency_review_required: "전송 내용을 다시 검토해 주세요.",
  dependency_context_changed: "프로젝트 연결이 변경되었습니다. 다시 선택한 뒤 분석해 주세요.",
  dependency_operation_failed: "의존성 분석이나 조회를 완료하지 못했습니다. 파일과 저장된 캐시 상태를 확인하고 다시 검토해 주세요.",
  definition_owner_reference_required: "비밀 및 API 환경 참조는 해당 연결 화면에서 변경해 주세요.",
  session_task_conflict: "세션이 참조하는 작업을 먼저 조정해 주세요.",
  unsupported_overlay_version: "지원하지 않는 로컬 설정 버전입니다. 기존 파일은 보존됩니다.",
  project_definition_changed: "프로젝트 정의나 참조 파일이 변경되었습니다. 다시 확인해 주세요.",
  project_definition_unavailable: "프로젝트 정의의 참조 파일을 읽지 못했습니다. 경로와 연결 상태를 확인해 주세요.",
  project_definition_limit: "프로젝트 정의의 파일 수나 크기가 허용 범위를 넘었습니다.",
  unsafe_project_definition: "프로젝트 밖이나 연결된 경로의 정의는 사용할 수 없습니다.",
  definition_preview_stale: "프로젝트 정의 확인이 만료되었습니다. 다시 검토해 주세요.",
  unsupported_manifest_version: "지원하지 않는 프로젝트 정의 버전입니다. 기존 파일은 보존됩니다.",
  invalid_manifest: "프로젝트 정의 JSON을 읽지 못했습니다. 기존 파일은 보존됩니다.",
  invalid_manifest_definition: "프로젝트 정의의 작업·도구·참조 경로를 확인해 주세요.",
  invalid_overlay: "이 컴퓨터의 프로젝트 설정을 읽지 못했습니다. 기존 파일은 보존됩니다.",
  stale_overlay_binding: "이 컴퓨터의 설정이 이전 프로젝트 연결을 사용합니다. 다시 검토해 주세요.",
  initializing: "저장된 정보를 불러오고 있습니다.",
  busy: "앞선 작업이 끝난 뒤 다시 시도해 주세요.",
  context_busy: "파일 또는 Git 작업이 진행 중입니다. 완료나 취소를 확인한 뒤 다시 시도해 주세요.",
  store_owner_busy: "다른 작업에서 저장소를 사용하고 있습니다.",
  legacy_import_busy: "기존 설정을 보관하는 작업이 진행 중입니다.",
  legacy_profiles_unavailable: "검증을 마친 Workbench 프로젝트 프로필이 필요합니다. 보관 내용을 다시 확인해 주세요.",
  invalid_imported_profile: "가져온 프로필 형식을 확인하지 못했습니다. 저장된 내용은 유지됩니다.",
  duplicate_imported_profile: "같은 보관본의 프로필이 이미 있습니다. 가져오기 검토를 다시 시작해 주세요.",
  invalid_legacy_choices: "프로필의 현재 상태에 맞는 처리 방법을 선택해 주세요.",
  legacy_profile_review_limit: "진행 중인 프로필 가져오기 검토를 완료하거나 취소해 주세요.",
  legacy_profile_review_stale: "프로필 가져오기 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  unknown_imported_profile: "가져온 프로필을 찾지 못했습니다. 프로젝트 목록을 새로 고쳐 주세요.",
  legacy_profile_target_missing: "이 프로필에는 선택한 환경의 폴더가 없습니다.",
  invalid_imported_profile_binding: "가져온 프로필의 프로젝트 연결을 확인하지 못했습니다. 기존 정보는 유지됩니다.",
  legacy_profile_binding_conflict: "이 프로필 또는 폴더가 다른 항목과 연결되어 있습니다. 기존 연결을 검토한 뒤 다시 시도해 주세요.",
  legacy_import_stale: "이전 보관 작업입니다. 진행 상태를 다시 확인해 주세요.",
  legacy_import_timeout: "기존 설정 확인 시간이 초과되었습니다. 원본은 유지됩니다.",
  legacy_import_cancelled: "기존 설정 보관을 취소했습니다.",
  legacy_path_unavailable: "기존 설정 폴더를 읽을 수 없습니다. 연결된 경로나 접근 권한을 확인해 주세요.",
  legacy_source_changed: "확인하는 동안 기존 설정이 바뀌었습니다. 기존 앱을 닫고 다시 시도해 주세요.",
  legacy_file_limit: "기존 설정 파일이 보관 크기 제한을 초과했습니다. 원본은 유지됩니다.",
  legacy_snapshot_unavailable: "설정을 보관할 수 없습니다. 저장 공간과 폴더 상태를 확인해 주세요.",
  legacy_snapshot_changed: "보관 파일이 변경되어 덮어쓰지 않았습니다. 원본은 유지됩니다.",
  legacy_snapshot_incomplete: "완료되지 않은 보관 작업입니다. 같은 원본으로 다시 시도해 주세요.",
  invalid_legacy_snapshot: "보관 기록을 검증하지 못했습니다. 기존 파일은 유지됩니다.",
  legacy_snapshot_limit: "보관 작업이 32개 한도에 도달했습니다. 기존 보관 파일은 유지됩니다.",
  store_pointer_changed: "저장소가 변경되었습니다. 앱을 다시 시작해 주세요.",
  invalid_registry: "프로젝트 목록을 읽지 못했습니다. 기존 파일을 확인해 주세요.",
  invalid_files_store: "편집기 설정이나 복구 파일을 읽지 못했습니다. 기존 파일을 확인해 주세요.",
  invalid_overview_store: "프로젝트 설정을 읽지 못했습니다. 기존 파일을 확인해 주세요.",
  project_probe_timeout: "폴더 확인 시간이 초과되었습니다. 연결 상태를 확인해 주세요.",
  project_object_unavailable: "폴더 또는 Git 정보를 읽지 못했습니다.",
  unsafe_project_object: "연결된 경로는 등록할 수 없습니다. 실제 폴더를 선택해 주세요.",
  native_path_transport_denied: "이 드라이브 연결을 확인할 수 없습니다. 실제 로컬 경로나 직접 선택한 Windows 공유 경로를 사용해 주세요.",
  project_object_changed: "확인한 폴더가 변경되었습니다. 다시 확인해 주세요.",
  project_preview_stale: "등록 확인이 만료되었습니다. 폴더를 다시 확인해 주세요.",
  stale_registry: "프로젝트 목록이 변경되었습니다. 새로 고친 뒤 다시 시도해 주세요.",
  stale_context: "프로젝트 연결이 변경되었습니다. 작업 폴더를 다시 선택해 주세요.",
  project_binding_changed: "등록한 폴더가 교체되었습니다. 폴더를 확인하고 경로를 다시 연결해 주세요.",
  context_selection_expired: "프로젝트 확인 시간이 초과되었습니다. 다시 선택해 주세요.",
  project_has_legacy_references: "이 프로젝트를 참조하는 항목이 있어 등록을 해제할 수 없습니다.",
  wsl_admission_required: "WSL 프로젝트 연결은 아직 사용할 수 없습니다.",
  file_selection_required: "파일 선택 버튼에서 열 파일을 선택해 주세요.",
  file_owner_path: "제품이 관리하는 설정과 승인 파일은 일반 편집기로 변경할 수 없습니다. 해당 설정 화면을 사용해 주세요.",
  project_selection_required: "개요에서 작업할 프로젝트를 선택해 주세요.",
  file_context_changed: "파일을 연 프로젝트가 변경되었습니다. 해당 프로젝트를 다시 선택해 주세요.",
  file_snapshot_changed: "파일 상태가 변경되었습니다. 다시 불러온 뒤 시도해 주세요.",
  file_changed: "디스크의 파일이 변경되었습니다. 다시 불러오거나 파일을 다시 선택해 주세요.",
  file_save_conflict: "파일이 변경되었거나 저장할 수 없습니다. 현재 내용을 보존한 채 파일 상태를 확인해 주세요.",
  file_rename_conflict: "파일 상태나 새 이름을 확인한 뒤 다시 시도해 주세요.",
  file_delete_conflict: "파일이 변경되어 삭제하지 않았습니다. 상태를 다시 확인해 주세요.",
  file_read_failed: "파일을 읽지 못했습니다. 연결 상태와 파일 크기·인코딩을 확인해 주세요.",
  file_target_unavailable: "이 파일의 실행 환경을 아직 연결하지 못했습니다.",
  unsafe_file_path: "연결된 경로 대신 실제 파일을 선택해 주세요.",
  file_limit: "열린 파일을 일부 닫은 뒤 다시 시도해 주세요.",
  file_path_limit: "이 파일의 경로가 너무 깊습니다.",
  invalid_file_choices: "최근 파일 정보를 읽지 못했습니다. 저장된 정보를 확인해 주세요.",
  files_store_changed: "편집기 저장소가 변경되었습니다. 앱을 다시 시작해 주세요.",
  files_session_changed: "저장된 세션이 변경되어 자동 저장을 멈췄습니다. 현재 편집을 저장한 뒤 프로젝트를 다시 선택하거나 앱을 다시 시작해 주세요.",
  legacy_session_unavailable: "Overview에서 Code Pad 보관본의 세션 파일을 먼저 확인해 주세요.",
  legacy_session_conflict: "현재 세션을 바꾸는 데 동의한 뒤 다시 검토해 주세요.",
  legacy_session_limit: "세션 또는 보관 기록 한도에 도달했습니다. 기존 내용은 유지됩니다.",
  legacy_session_documents_open: "Files의 열린 탭을 모두 닫은 뒤 세션 가져오기를 검토해 주세요.",
  legacy_session_no_files: "현재 프로젝트에서 복원할 파일이 없습니다. 해당 프로젝트를 선택하거나 대상 파일을 파일 선택 창으로 열고 탭을 닫은 뒤 다시 검토해 주세요.",
  legacy_session_review_limit: "진행 중인 세션 가져오기 검토를 완료하거나 취소해 주세요.",
  legacy_session_review_stale: "세션 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  files_initialize_failed: "편집기 저장소를 준비하지 못했습니다. 저장된 정보를 확인해 주세요.",
  files_recovery_changed: "복구 버퍼가 다른 작업에서 변경되었습니다. 현재 버퍼를 유지하고 다시 검토해 주세요.",
  legacy_recovery_unavailable: "확인한 보관본에서 미저장 버퍼를 읽지 못했습니다.",
  legacy_recovery_no_files: "현재 프로젝트나 직접 선택한 파일에 해당하는 미저장 버퍼가 없습니다. 원본은 보관했습니다.",
  legacy_recovery_documents_open: "열린 파일 탭과 복구 검토를 모두 닫은 뒤 다시 시도해 주세요.",
  legacy_recovery_conflict: "같은 파일의 다른 버퍼를 바꾸려면 내용을 확인하고 교체를 선택해 주세요.",
  legacy_recovery_review_limit: "진행 중인 복구 버퍼 가져오기를 완료하거나 취소해 주세요.",
  legacy_recovery_review_stale: "복구 버퍼 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  legacy_recovery_limit: "복구 버퍼 또는 보관 이력의 한도에 도달했습니다. 기존 내용을 보존했습니다.",
  recovery_preview_stale: "복구 대상이 변경되었습니다. 미리보기를 다시 확인해 주세요.",
  recovery_unavailable: "저장된 복구 내용을 확인하지 못했습니다.",
  lsp_recovery_unavailable: "이름 변경 복구 기록을 확인하지 못했습니다. 원본은 보존했습니다.",
  lsp_recovery_limit: "진행 중인 복구 검토를 먼저 완료하거나 취소해 주세요.",
  lsp_recovery_stale: "복구 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  lsp_recovery_conflict: "대상 파일 탭을 닫고 다시 검토해 주세요. 파일·백업·접근 권한이 변경된 경우 복원을 거부하고 원본을 보존합니다.",
  lsp_operation_cancelled: "LSP 작업이 취소되었습니다.",
  lsp_execution_approval_required: "현재 프로젝트의 언어 서버 실행 설정을 검토하고 승인해 주세요.",
  lsp_settings_save_required: "언어 서버 사용을 선택하고 설정을 저장한 뒤 실행을 검토해 주세요.",
  legacy_lsp_unavailable: "확인한 보관본에서 LSP 설정을 읽지 못했습니다.",
  legacy_lsp_documents_open: "열린 파일 탭과 복구 검토를 모두 닫은 뒤 LSP 설정을 가져와 주세요.",
  legacy_lsp_conflict: "현재 LSP 설정을 확인하고 교체를 선택해 주세요.",
  legacy_lsp_review_limit: "진행 중인 LSP 설정 가져오기를 완료하거나 취소해 주세요.",
  legacy_lsp_review_stale: "LSP 설정 검토가 만료되었거나 이미 사용되었습니다. 다시 검토해 주세요.",
  legacy_lsp_limit: "LSP 설정 보관 이력이 한도에 도달했습니다. 기존 내용을 보존했습니다.",
  lsp_config_changed: "LSP 설정이 변경되었습니다. 설정 화면을 다시 열어 확인해 주세요.",
  lsp_config_future: "현재 버전에서 읽을 수 없는 LSP 설정을 보존했습니다.",
  lsp_config_invalid: "LSP 설정을 확인해 주세요.",
  lsp_config_recovery_required: "손상된 LSP 설정은 명시적으로 복구해야 저장할 수 있습니다.",
  lsp_approval_changed: "LSP 실행 승인이 변경되었습니다. 다시 검토해 주세요.",
  lsp_approval_invalid: "저장된 LSP 실행 승인을 확인하지 못했습니다.",
  lsp_approval_future: "현재 버전에서 읽을 수 없는 LSP 실행 승인을 보존했습니다.",
  lsp_review_expired: "LSP 실행 검토가 만료되었습니다. 다시 검토해 주세요.",
  lsp_review_busy: "진행 중인 LSP 실행 검토를 먼저 완료하거나 취소해 주세요.",
  lsp_context_changed: "LSP 프로젝트 또는 실행 근거가 변경되었습니다. 다시 검토해 주세요.",
  lsp_command_unavailable: "선택한 언어 서버와 runtime 경로를 확인해 주세요.",
  lsp_installation_unavailable: "관리형 언어 서버 설치 상태를 확인해 주세요.",
  lsp_source_transport_denied: "선택한 프로젝트와 연결된 로컬 실행 경로를 사용해 주세요.",
  lsp_source_path_invalid: "LSP 실행 경로에 연결된 경로나 지원하지 않는 파일이 있습니다.",
  lsp_source_unavailable: "LSP 실행 파일을 읽지 못했습니다. 경로와 접근 권한을 확인해 주세요.",
  lsp_source_limit: "LSP 실행 검토 범위가 허용된 크기를 초과했습니다.",
  lsp_sources_changed: "LSP 실행 파일이 변경되었습니다. 다시 검토해 주세요.",
  lsp_executable_format_unsupported: "Windows 실행 파일을 직접 선택하거나 관리형 Node 서버를 사용해 주세요.",
  lsp_target_unavailable: "이 실행 대상의 LSP 연결을 아직 사용할 수 없습니다.",
  lsp_busy: "다른 LSP 작업이 진행 중입니다. 잠시 후 다시 시도해 주세요.",
  lsp_shutdown_unconfirmed: "언어 서버 종료를 아직 확인하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  lsp_already_running: "언어 서버가 이미 실행 중입니다.",
  lsp_not_running: "언어 서버가 실행 중이 아닙니다.",
  lsp_start_in_progress: "언어 서버 시작이 이미 진행 중입니다.",
  lsp_disabled: "LSP가 비활성화되어 있습니다.",
  lsp_feature_unsupported: "언어 서버가 이 기능을 지원하지 않습니다.",
  lsp_unavailable: "언어 서버 작업을 완료하지 못했습니다. 실행 상태와 검토한 설정을 확인해 주세요.",
  lsp_install_busy: "다른 LSP 설치 작업이 진행 중입니다.",
  lsp_index_corrupt: "관리형 서버 설치 목록 복구가 필요합니다",
  lsp_install_path_unsafe: "관리형 서버의 설치·보관 폴더에 연결된 경로나 지원하지 않는 파일이 있습니다.",
  lsp_install_io_unavailable: "관리형 서버의 설치·보관 파일을 읽거나 쓸 수 없습니다. 폴더 상태를 확인해 주세요.",
  lsp_install_status_invalid: "관리형 서버 상태 응답을 확인하지 못했습니다.",
  lsp_install_failed: "관리형 서버 설치를 완료하지 못했습니다. 파일 검증과 연결 상태를 확인해 주세요.",
  lsp_archive_selection_invalid: "archive 선택이 만료되었습니다. 파일을 다시 선택해 주세요.",
  lsp_archive_changed: "선택한 archive가 변경되었습니다. 파일을 다시 선택해 주세요.",
  lsp_archive_unsafe: "연결된 경로 대신 실제 archive 파일을 선택해 주세요.",
  lsp_archive_limit: "archive 선택은 32개·합계 512 MiB까지 가능합니다.",
  request_expired: "작업 대기 시간이 초과되었습니다. 다시 시도해 주세요.",
};
export function issueMessage(issue: string): string { return issues[issue] ?? "작업을 완료하지 못했습니다. 상태를 확인하고 다시 시도해 주세요."; }
export async function nativeCall<T>(component: string, method: string, args: Record<string, unknown> = {}, route = "overview"): Promise<T> {
  const description = await describe("workspace");
  return componentCall(description, component, method, args, route);
}
/** Feature actions bind the description currently displayed by the caller. */
export async function componentCall<T>(description: Description, component: string, method: string, args: Record<string, unknown>, route: string): Promise<T> {
  const header = makeRequest(description.handshake, route, Date.now(), description.context);
  // Stay inside the native 30-second ceiling across renderer/native clock precision.
  if (component === "workspace.dependencies" || component === "workspace.source" || component === "workspace.lsp") header.deadlineMs += 24_000;
  const provenance = { product: "workspace", component, requestId: header.requestId, revision: catalog.catalogRevision };
  let response: {operation: unknown; value: T & {issue?: string}};
  try {response = await invoke("plugin:workspace|execute", {request:{header, component, method, args}});}
  catch (problem) {throw new WorkspaceOperationError(problemMessage(problem, provenance));}
  if (!response || !isOperation(response.operation, provenance)) throw new Error("응답을 확인하지 못했습니다.");
  if (response.operation.outcome.state !== "succeeded") throw new WorkspaceOperationError(issueMessage(response.value?.issue ?? "operation_failed"));
  return response.value;
}
