import {StrictMode} from "react";
import {act,cleanup,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import WorkspaceTemplateManager from "./WorkspaceTemplateManager";
import {nativeCall} from "./native";
import type {Registry} from "./RegistryGate";
vi.mock("./native",()=>({nativeCall:vi.fn()}));
const call=vi.mocked(nativeCall);
const template={id:"native-template",name:"보관한 기본값",windowsPath:null,wsl:null,gitRoot:null,expectedPorts:[4321],runManagerServiceIds:["service"]};
const entry={id:"record",sourceSnapshotId:"a".repeat(64),template};
const registry:Registry={revision:7,projects:[],worktrees:[],importedTemplates:[entry]};
beforeEach(()=>{call.mockReset();call.mockResolvedValue({});});
afterEach(cleanup);
it("pins the opening revision and preserves edits after a stale save without forging origin",async()=>{
  const saved=vi.fn(async()=>{}),busy=vi.fn();
  const props={disabled:false,onSaved:saved,onBusyChange:busy};
  const rendered=render(<StrictMode><WorkspaceTemplateManager {...props} registry={registry}/></StrictMode>);
  fireEvent.click(screen.getByText("보관한 기본값",{selector:"summary"}));
  fireEvent.click(screen.getByRole("button",{name:"템플릿 수정"}));
  fireEvent.change(screen.getByLabelText("템플릿 이름"),{target:{value:"작성 중"}});
  rendered.rerender(<StrictMode><WorkspaceTemplateManager {...props} registry={{...registry,revision:8}}/></StrictMode>);
  call.mockRejectedValueOnce(new Error("목록이 변경되었습니다."));
  fireEvent.click(screen.getByRole("button",{name:"템플릿 저장"}));
  expect(await screen.findByRole("alert")).toHaveProperty("textContent","목록이 변경되었습니다.");
  expect(screen.getByLabelText("템플릿 이름")).toHaveProperty("value","작성 중");
  expect(call).toHaveBeenCalledWith("workspace.registry","save_template",{revision:7,id:"record",template:{...template,name:"작성 중"}});
  expect(saved).not.toHaveBeenCalled();
  expect(busy).toHaveBeenLastCalledWith(true);
  fireEvent.click(screen.getByRole("button",{name:"템플릿 편집 취소"}));
  await waitFor(()=>expect(busy).toHaveBeenLastCalledWith(false));
});
it("validates new drafts and requires explicit archive and restore saves",async()=>{
  const saved=vi.fn(async()=>{}),busy=vi.fn();
  const props={disabled:false,onSaved:saved,onBusyChange:busy};
  const rendered=render(<WorkspaceTemplateManager {...props} registry={registry}/>);
  fireEvent.click(screen.getByRole("button",{name:"새 템플릿"}));
  fireEvent.change(screen.getByLabelText("템플릿 이름"),{target:{value:"로컬"}});
  fireEvent.change(screen.getByLabelText("기본 포트 (쉼표로 구분)"),{target:{value:"99999"}});
  fireEvent.submit(screen.getByRole("form",{name:"템플릿 편집"}));
  expect(await screen.findByRole("alert")).toBeTruthy();expect(call).not.toHaveBeenCalled();
  fireEvent.change(screen.getByLabelText("기본 포트 (쉼표로 구분)"),{target:{value:"5173"}});
  await act(async()=>fireEvent.submit(screen.getByRole("form",{name:"템플릿 편집"})));
  expect(call).toHaveBeenCalledWith("workspace.registry","save_template",{revision:7,id:null,template:{...template,id:"",name:"로컬",expectedPorts:[5173],runManagerServiceIds:[]}});
  fireEvent.click(screen.getByText("보관한 기본값",{selector:"summary"}));
  fireEvent.click(screen.getByRole("button",{name:"템플릿 보관"}));
  expect(call.mock.calls.filter(([,method])=>method==="archive_template")).toHaveLength(0);
  rendered.rerender(<WorkspaceTemplateManager {...props} registry={{...registry,revision:8}}/>);
  await act(async()=>fireEvent.click(within(screen.getByRole("region",{name:"템플릿 보관 확인"})).getByRole("button",{name:"템플릿 보관 확인"})));
  expect(call).toHaveBeenCalledWith("workspace.registry","archive_template",{revision:7,id:"record"});
  rendered.rerender(<WorkspaceTemplateManager {...props} registry={{...registry,revision:9,importedTemplates:[{...entry,archived:true}]}}/>);
  fireEvent.click(screen.getByRole("button",{name:"템플릿 복원 검토"}));
  expect(screen.getByLabelText("기본 포트 (쉼표로 구분)")).toHaveProperty("value","4321");
  expect(call.mock.calls.filter(([,method])=>method==="save_template")).toHaveLength(1);
  await act(async()=>fireEvent.click(screen.getByRole("button",{name:"템플릿 저장"})));
  expect(call).toHaveBeenLastCalledWith("workspace.registry","save_template",{revision:9,id:"record",template});
});
