const issues:Record<string,string>={
  wsl_lsp_installed_target_required: "WSL 배포판에 설치된 언어 서버 또는 Node 진입 파일을 직접 지정해 주세요.",
  wsl_lsp_language_unsupported: "이 WSL 언어 서버의 언어는 아직 지원하지 않습니다.",
  wsl_distro_stopped: "WSL 배포판이 중지되어 있습니다. 목록을 새로 고친 뒤 시작 여부를 선택해 주세요.",
  wsl_distro_missing: "WSL 배포판 등록을 찾을 수 없습니다. 목록을 새로 고쳐 주세요.",
  wsl_storage_path_unsafe: "WSL 저장 폴더 경로에 링크나 접근할 수 없는 폴더가 있습니다. 배포판 저장 위치를 확인해 주세요.",
  wsl_storage_unavailable: "WSL 배포판 저장 폴더의 식별 정보를 읽지 못했습니다. 경로와 접근 권한을 확인해 주세요.",
  wsl_request_cancelled: "WSL 파일 작업이 취소되었습니다. 편집 내용은 유지됩니다.",
  wsl_registry_changed: "WSL 배포판이나 디스크가 바뀌었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_registry_read_changed: "WSL 등록 정보가 갱신 중입니다. 잠시 후 폴더 연결을 다시 검토해 주세요.",
  wsl_registry_entry_missing: "조회 중 WSL 등록 항목이 사라졌습니다. 배포판 목록을 새로 고쳐 주세요.",
  wsl_registry_list_changed: "WSL 배포판 목록이 갱신 중입니다. 잠시 후 다시 확인해 주세요.",
  wsl_shutdown_unconfirmed: "WSL 파일 연결의 종료를 확인하지 못했습니다. 편집 내용을 보존하고 다시 시도해 주세요.",
  wsl_backing_path_unsafe: "WSL 가상 디스크 경로가 바뀌었습니다. 배포판 저장 위치를 확인해 주세요.",
  wsl_backing_unavailable: "WSL 가상 디스크의 식별 정보를 읽지 못했습니다.",
  wsl_backing_object_changed: "WSL 가상 디스크가 교체되었습니다. 폴더 연결을 다시 검토해 주세요.",
  legacy_profile_distro_mismatch: "프로필에 보관된 이름과 일치하는 WSL 배포판을 선택하세요.",
  wsl_reveal_path_unavailable: "이 WSL 파일 이름은 Windows 탐색기에서 표시할 수 없습니다.",
  wsl_retained_registration_changed: "WSL 배포판의 등록 값이 바뀌었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_registration_changed: "WSL 배포판 등록이 교체되었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_storage_object_changed: "WSL 배포판 저장 폴더가 교체되었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_helper_unavailable: "WSL 연결 파일을 확인하지 못했습니다. Workspace 설치 상태를 확인해 주세요.",
  wsl_helper_changed: "WSL 연결 파일이 변경되었습니다. Workspace를 다시 설치한 뒤 확인해 주세요.",
  wsl_identity_unavailable: "이 WSL 파일시스템의 폴더 식별 정보를 확인할 수 없습니다.",
  wsl_root_changed: "WSL 폴더나 저장소가 바뀌었습니다. 폴더 연결을 다시 검토해 주세요.",
  wsl_context_invalid: "WSL 프로젝트 문맥을 확인하지 못했습니다. 프로젝트를 다시 선택해 주세요.",
  wsl_context_required: "WSL 파일을 열기 전에 프로젝트 연결을 확인해 주세요.",
  wsl_native_filesystem_required: "배포판의 기본 Linux 파일시스템 폴더를 선택해 주세요. 다른 마운트의 파일은 아직 지원하지 않습니다.",
  wsl_filesystem_unavailable: "WSL 파일시스템 정보를 읽지 못했습니다. 배포판 상태를 확인해 주세요.",
  wsl_root_expired: "WSL 폴더 검토가 만료되었습니다. 폴더를 다시 확인해 주세요.",
  wsl_connection_closed: "WSL 연결이 종료되었습니다. 배포판 상태를 확인하고 다시 연결해 주세요.",
  wsl_timeout: "WSL 연결 시간이 초과되었습니다. 배포판 상태를 확인해 주세요.",
  wsl_operation_failed: "WSL 폴더를 확인하지 못했습니다. 경로와 접근 권한을 확인해 주세요.",
  wsl_admission_required: "WSL 프로젝트 연결은 아직 사용할 수 없습니다.",
};
export function wslIssueMessage(issue:string):string|undefined{return issues[issue];}
