const messages: Record<string, string> = {
  quick_capture_sensitive: "민감한 정보가 포함되어 있어 저장하지 않았습니다",
  quick_capture_body_required: "빠른 캡처 본문을 입력하세요",
  quick_capture_invalid: "빠른 캡처 입력이 올바르지 않습니다",
  quick_capture_title_limit: "제목은 UTF-8 800바이트·200자 이내로 입력하세요",
  quick_capture_body_limit: "본문은 LF 기준 64 KiB(원문 128 KiB) 이내로 입력하세요",
  quick_capture_tag_count: "태그는 최대 20개까지 입력하세요",
  quick_capture_tag_limit: "태그 하나는 UTF-8 192바이트·48자 이내로 입력하세요",
  quick_capture_tags_limit: "태그 전체는 UTF-8 1 KiB 이내로 입력하세요",
  quick_capture_tag_invalid: "태그에 줄바꿈·쉼표·대괄호·따옴표를 사용할 수 없습니다",
  quick_capture_save_failed: "빠른 캡처를 저장하지 못했습니다",
  journal_unavailable: "복구용 임시 저장을 기록하지 못했습니다. 편집 내용은 유지됩니다.",
  journal_limit: "복구용 임시 저장이 8개로 가득 찼습니다. 남은 복구본을 복원하거나 버린 뒤 다시 편집해 주세요.",

  privacy_rules_save_failed: "개인정보 규칙을 저장하지 못했습니다. 이전 규칙을 계속 사용합니다.",
  privacy_rules_invalid: "저장된 개인정보 규칙을 읽지 못해 창 제목 저장을 멈췄습니다. 규칙을 다시 저장해 주세요.",
  privacy_redaction_failed: "기존 기록에 규칙을 적용하지 못했습니다. 기록은 바뀌지 않았습니다.",
  draft_stale: "저장 위치나 초안 상태가 바뀌었습니다. 새로 준비해 주세요.",
  draft_busy: "다른 초안을 미리보기 중입니다.",
  draft_invalid: "초안 요청의 형식이나 대상을 확인해 주세요.",
  draft_unavailable: "초안을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  note_applied_postprocessing_failed:
    "파일 작업은 반영했지만 후처리를 완료하지 못했습니다. 다시 실행하기 전에 디스크 상태를 확인해 주세요.",
  note_commit_unknown: "파일 작업의 반영 상태를 확정하지 못했습니다. 다시 실행하기 전에 디스크 상태를 확인해 주세요.",
  metadata_limit: "노트 목록의 항목·깊이·크기 제한을 초과했습니다. 기존 목록을 유지합니다.",
  metadata_timeout: "노트 목록 탐색 시간이 초과되었습니다. 기존 목록을 유지합니다.",
  metadata_cancelled: "노트 목록 탐색이 취소되었습니다. 기존 목록을 유지합니다.",
  metadata_incomplete: "노트 목록을 완전히 읽지 못했습니다. 기존 목록을 유지합니다.",
  metadata_stale: "탐색 중 저장 위치가 변경되었습니다. 목록을 다시 불러와 주세요.",
  metadata_busy: "이전 목록 탐색이 종료되는 중입니다. 잠시 후 다시 불러와 주세요.",
  note_conflict: "파일이 외부에서 변경되었습니다. 비교 후 다시 저장해 주세요.",
  note_unavailable: "파일을 읽거나 저장하지 못했습니다. 편집 내용은 유지됩니다.",
  vault_change_invalid: "저장소 변경 정보를 확인할 수 없습니다. 현재 연결과 원본 파일은 유지됩니다.",
  vault_change_save_failed: "저장소 연결을 저장하지 못했습니다. 공간과 권한을 확인하고 다시 시도해 주세요.",
  vault_change_stale: "폴더나 연결 정보가 바뀌었거나 미리보기가 만료되었습니다. 다시 확인해 주세요.",
  vault_change_unavailable: "선택한 노트 폴더를 확인할 수 없습니다. 존재하는 폴더와 연결 상태를 확인해 주세요.",
  vault_change_conflict: "예약한 가져오기 또는 저장소 변경을 먼저 마치거나 취소해 주세요.",
  vault_change_same: "이미 사용하고 있는 노트 폴더입니다.",
  vault_change_timeout: "폴더 확인이 제한 시간을 넘었습니다. 변경을 취소하고 현재 저장소로 계속할 수 있습니다.",
  search_stale: "검색 결과가 오래되었거나 파일 연결이 바뀌었습니다. 다시 검색해 주세요.",
  import_invalid: "가져오기 데이터의 내용이나 형식을 확인하지 못했습니다. 원본과 현재 데이터를 유지했습니다.",
  import_schema_unsupported: "이전 데이터의 형식을 지원하지 않습니다. 원본과 현재 저장소를 유지했습니다.",
  import_source_changed: "미리보기 이후 이전 앱의 데이터가 바뀌었습니다. 다시 준비해 주세요.",
  import_restart_required: "현재 노트를 저장하고 앱을 다시 시작한 뒤 가져오기를 진행해 주세요.",
  import_limit_exceeded:
    "가져오기 크기나 항목 수의 한도를 넘었습니다. 원본을 유지했습니다. 완료하지 않은 준비 작업도 확인해 주세요.",
  import_disk_full: "가져오기 사본과 복구 데이터를 보관할 여유 공간이 부족합니다.",
  import_timed_out: "가져오기가 제한 시간을 넘었습니다. 이전 앱을 닫고 다시 준비해 주세요.",
  legacy_writer_active:
    "이전 Knowledge 앱을 완전히 종료한 뒤 다시 적용해 주세요. 같은 노트를 동시에 수정할 수 없습니다.",
  vault_owner_busy: "다른 Knowledge 설치가 이 노트 저장소를 사용 중입니다. 해당 앱을 종료한 뒤 다시 시도해 주세요.",
  tray_unavailable: "트레이를 사용할 수 없어 설정을 변경하지 않았습니다.",
  close_policy_save_failed: "종료 설정을 저장하지 못했습니다. 이전 설정을 유지했습니다.",
  target_exists: "같은 경로의 파일이 이미 있습니다. 다시 확인해서 열어 주세요.",
  vault_unavailable: "노트 저장소에 연결할 수 없습니다. 경로와 연결 상태를 확인해 주세요.",
  invalid_request: "요청을 확인해 주세요.",
  setup_required: "저장소를 먼저 준비해 주세요.",
  busy: "다른 작업을 마친 뒤 다시 시도해 주세요.",
  future_schema: "더 최신 버전의 저장소입니다. 원본을 유지했습니다.",
  store_invalid: "저장소 정보를 확인할 수 없습니다. 기존 데이터는 유지됩니다.",
  consent_save_failed: "수집 설정을 저장하지 못했습니다. 현재 수집 상태를 확인하고 다시 시도해 주세요.",
  autostart_owner_conflict: "다른 실행 파일의 시작프로그램 등록이 있어 변경하지 않았습니다.",
  provider_unavailable: "연결할 수 없습니다. 현재 내용은 유지됩니다.",
  vault_binding_unavailable: "저장소 연결을 확인할 수 없습니다. 현재 저장소를 유지했습니다.",
  restart_required: "저장소 초기화를 완료하지 못했습니다. 앱을 다시 시작해 주세요.",
  cancelled: "작업을 취소했습니다.",
  preview_expired: "미리보기가 만료되었습니다. 새로 준비해 주세요.",
  preview_stale: "미리보기가 오래되었습니다. 다시 확인해 주세요.",
};
export function issueError(issue: unknown): Error {
  const known = typeof issue === "string" && Object.prototype.hasOwnProperty.call(messages, issue);
  const error = new Error(known ? messages[issue] : "작업을 완료하지 못했습니다. 입력과 저장 위치를 확인해 주세요.");
  if (known) error.name = issue;
  return error;
}
