import type { NotesIssue } from "../generated/NotesIssue";
export const notesMessages: Record<NotesIssue, string> = {
  clipboard_unavailable: "클립보드 내용을 읽지 못했습니다. 다시 시도해 주세요.",
  component_worker_unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  draft_busy: "다른 초안을 미리보기 중입니다.",
  draft_expired: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  draft_invalid: "초안 요청의 형식이나 대상을 확인해 주세요.",
  draft_limit: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  draft_stale: "저장 위치나 초안 상태가 바뀌었습니다. 새로 준비해 주세요.",
  draft_unavailable: "초안을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  opener_unavailable: "외부 링크를 열지 못했습니다.",
  provider_unavailable: "연결할 수 없습니다. 현재 내용은 유지됩니다.",
  summary_busy: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_expired: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_limit: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_preview_busy: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_stale: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_store_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_store_unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  summary_unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  vault_binding_unavailable: "저장소 연결을 확인할 수 없습니다. 현재 저장소를 유지했습니다.",
  component_args_invalid: "요청을 확인해 주세요.",
  component_response_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  component_state_conflict: "저장소 초기화를 완료하지 못했습니다. 앱을 다시 시작해 주세요.",
  component_storage_unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  component_store_exists: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  daily_preview_stale: "미리보기가 오래되었습니다. 다시 확인해 주세요.",
  daily_target_exists: "같은 경로의 파일이 이미 있습니다. 다시 확인해서 열어 주세요.",
  daily_vault_unavailable: "노트 저장소에 연결할 수 없습니다. 경로와 연결 상태를 확인해 주세요.",
  daily_write_failed: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  draft_delivery_busy: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  draft_delivery_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  draft_delivery_unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  import_row_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  journal_limit: "복구용 임시 저장이 8개로 가득 찼습니다. 남은 복구본을 복원하거나 버린 뒤 다시 편집해 주세요.",
  journal_unavailable: "복구용 임시 저장을 기록하지 못했습니다. 편집 내용은 유지됩니다.",
  knowledge_draft_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  metadata_busy: "이전 목록 탐색이 종료되는 중입니다. 잠시 후 다시 불러와 주세요.",
  metadata_cancelled: "노트 목록 탐색이 취소되었습니다. 기존 목록을 유지합니다.",
  metadata_incomplete: "노트 목록을 완전히 읽지 못했습니다. 기존 목록을 유지합니다.",
  metadata_limit: "노트 목록의 항목·깊이·크기 제한을 초과했습니다. 기존 목록을 유지합니다.",
  metadata_stale: "탐색 중 저장 위치가 변경되었습니다. 목록을 다시 불러와 주세요.",
  metadata_timeout: "노트 목록 탐색 시간이 초과되었습니다. 기존 목록을 유지합니다.",
  note_applied_postprocessing_failed:
    "파일 작업은 반영했지만 후처리를 완료하지 못했습니다. 다시 실행하기 전에 디스크 상태를 확인해 주세요.",
  note_commit_unknown: "파일 작업의 반영 상태를 확정하지 못했습니다. 다시 실행하기 전에 디스크 상태를 확인해 주세요.",
  note_conflict: "파일이 외부에서 변경되었습니다. 비교 후 다시 저장해 주세요.",
  note_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  note_unavailable: "파일을 읽거나 저장하지 못했습니다. 편집 내용은 유지됩니다.",
  preview_expired: "미리보기가 만료되었습니다. 새로 준비해 주세요.",
  preview_stale: "미리보기가 오래되었습니다. 다시 확인해 주세요.",
  quick_capture_body_required: "빠른 캡처 본문을 입력하세요",
  quick_capture_save_failed: "빠른 캡처를 저장하지 못했습니다",
  search_stale: "검색 결과가 오래되었거나 파일 연결이 바뀌었습니다. 다시 검색해 주세요.",
  search_unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  session_summary_invalid: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  session_summary_unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  unavailable: "노트 작업을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
  vault_change_stale: "폴더나 연결 정보가 바뀌었거나 미리보기가 만료되었습니다. 다시 확인해 주세요.",
  vault_change_unavailable: "선택한 노트 폴더를 확인할 수 없습니다. 존재하는 폴더와 연결 상태를 확인해 주세요.",
  quick_capture_body_limit: "본문은 LF 기준 64 KiB(원문 128 KiB) 이내로 입력하세요",
  quick_capture_invalid: "빠른 캡처 입력이 올바르지 않습니다",
  quick_capture_sensitive: "민감한 정보가 포함되어 있어 저장하지 않았습니다",
  quick_capture_tag_count: "태그는 최대 20개까지 입력하세요",
  quick_capture_tag_invalid: "태그에 줄바꿈·쉼표·대괄호·따옴표를 사용할 수 없습니다",
  quick_capture_tag_limit: "태그 하나는 UTF-8 192바이트·48자 이내로 입력하세요",
  quick_capture_tags_limit: "태그 전체는 UTF-8 1 KiB 이내로 입력하세요",
  quick_capture_title_limit: "제목은 UTF-8 800바이트·200자 이내로 입력하세요",
};
