[package]
name = "devbox-workspace"
version = "0.8.0"
publish = false
edition = "2021"
authors = ["jihoon22.lee"]
description = "Devbox Workspace development product shell"

[lib]
name = "devbox_workspace_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
product-shell-tauri = { path = "../../../crates/product-shell-tauri" }
